h2oai/wave

website/docusaurus.config.js
website/package-lock.json
website/package.json
website/src/css/custom.css
website/src/theme/Footer/index.js

* Added a notice that complies with rest of H2O pages - https://www.h2o.ai/
* LocalStorage is used to not bother user that has already dismissed the notice.
* Removed the red color as I consider it being a leftover from previous design.
cc @NidhiMehta

feat: add gdpr notice to docs

---

website/src/theme/Footer/index.js

fix(docs): server side generate fail due to client only object used

---

py/examples/table_markdown_pandas.py
py/examples/tour.conf

Addresses #416 by duplicating Table / Markdown but changing the data source to a dataframe, and then formatting that object appropriately for non-interactive dataframe display

Display Dataframes

---

py/sync_examples.py

fix(docs): remove extra /examples from gallery link

---

website/docs/enterprise/developer-guide.md

OIDC configuration for HAC can be enabled by using the Runtime field `EnableOIDC = true`

docs: document enable enterprise oidc

---

py/examples/nav.py
py/h2o_wave/types.py
py/h2o_wave/ui.py
ui/src/nav.test.tsx
ui/src/nav.tsx

closes #376 
1. - [x] Setup the project.
2. - [x] Find nav.tsx.
3. - [x] Implement needed feature.
4. - [x] run make generate from project root - this generates python API.
5. - [x] Use your newly implemented prop to showcase its capabilities.
6. - [x] Add unit tests.

feat: add disabled prop to nav item #376

---

py/sync_examples.py
website/docusaurus.config.js

For https://github.com/h2oai/wave/issues/423

Add TOC for Wave examples

---

website/docs/security.md

If PR merged, the `security.md` docs will be updated.
Closes #437

Extend docs for OIDC flag example

---

.github/workflows/release.yml
Makefile
py/Makefile
py/conda/meta.yaml
py/setup.py

Closes https://github.com/h2oai/wave/issues/399

Github actions pipeline to cut a release in Wave

---

.github/workflows/publish-docs.yml
Makefile
py/Makefile

Pipeline to publish docs fixes without a wave release

feat: pipeline to publish docs

---

py/examples/breadcrumbs.py
ui/src/breadcrumbs.tsx

style: center breadcrumb component vertically #337

---

.github/workflows/release.yml

Set GITHUB_TOKEN as pipeline global env

fix: Set github token for conda publish step

---

py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
ui/src/meta.tsx

docs: meta icon not working in Safari #548

---

ui/src/frame.tsx

fix: use frame absolute positioning only for frame cards, not form items #558

---

ui/src/chat_room.tsx
ui/src/footer.tsx
ui/src/form.tsx
ui/src/frame.tsx
ui/src/grid.tsx
ui/src/header.tsx
ui/src/image.tsx
ui/src/index.scss
ui/src/large_bar_stat.tsx
ui/src/large_stat.tsx
ui/src/list.tsx
ui/src/list_item1.tsx
ui/src/markdown.tsx
ui/src/markup.tsx
ui/src/pixel_art.tsx
ui/src/plot.tsx
ui/src/progress_table_cell_type.tsx
ui/src/section.tsx
ui/src/small_series_stat.tsx
ui/src/small_stat.tsx
ui/src/stat_list.tsx
ui/src/stat_table.tsx
ui/src/stats.tsx
ui/src/tall_gauge_stat.tsx
ui/src/tall_series_stat.tsx
ui/src/vega.tsx
ui/src/wide_bar_stat.tsx
ui/src/wide_gauge_stat.tsx
ui/src/wide_series_stat.tsx

chore: prefix font weights and sizes to prevent conflicts with arbitrary libs #525

---

website/blog/2021-02-12-release.md

Change duplicate `on_heads` to `on_tails`.

Fix typo in 2021-02-12-release.md

---

README.md

Update README.md to include AI Apps

---

ui/src/dialog.tsx

Remove special-cased dialog footer

---

ui/src/plot.tsx

fix: trigger plot events only if selected #616

---

r/R/ui.R
tools/wavegen/src/wavegen.ts

Fixed the NULL variable remove in `ui.R`

R NULL fix

---

py/examples/button.py
py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
ui/src/button.tsx

Icon support for buttons

---

py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
ui/src/table.tsx

Adds checkbox_visibility option.
Also fixed a minior centering bug for checkboxes.
Closes #713

feat(table): checkbox visibility #713

---

ui/src/.wavegen

fix: ignore ui.ts during wavegen

---

py/examples/picker.py

Picker example was failing, values needs to be a list, not a single string

Fix data type in Tour example

---

py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
ui/src/file_upload.tsx

feat: Set default label and update docstring #788

---

ui/src/file_upload.tsx

feat: Use response error message #772

---

ui/src/dialog.tsx
ui/src/file_upload.test.tsx

* fixes broken file upload test
* Puts back client side dialog close in addition to the server side one introduced in #803

fix: UI unit tests

---

website/src/theme/Footer/index.js

Use display none for GDPR notice

---

website/blog/2021-06-15-ml-release.md

A new blog post for Wave ML, an overview of what was added.
Thanks @vopani and @tkmaker for review.

Add a new Wave ML blog post

---

py/examples/ml_h2o_algo.py
py/examples/tour.conf

This PR adds an example of using WaveML with an Algo type.
Closes https://github.com/h2oai/wave-ml/issues/62
Also added a minor improvement in categorical column choices based on this fix: https://github.com/h2oai/wave-ml/pull/59

WaveML H2O-3 Algo example

---

ui/src/header.test.tsx
ui/src/header.tsx
ui/src/nav.tsx

feat: close sidenav after clicking menu item #355

---

ui/src/table.test.tsx
ui/src/table.tsx

* Added default sorting for string | number | date types.
* Fixed minor deprecation warning for small_series_stat.
* Added unit tests.
Closes #336

Sort table group titles when grouped

---

py/examples/message_bar.py
ui/src/markdown.tsx
ui/src/message_bar.tsx

Generated HTML code has some default margins for some of the elements what does not align with default message bar type icon, had to adjust first-child / only-child appropriately.
Closes #356

Markdown / HTML within message_bar component

---

website/blog/2021-09-13-community-content.md

I was blocked in building the docs locally (#991 #990), so this needs to be still be reviewed for look & feel in the website. Also happy for content feedback.

docs: Add Big Data Visualizer community content blog post

---

ui/package.json
ui/src/spinbox.test.tsx
ui/src/spinbox.tsx

* User should be able to enter decimal points and increment/decrement without rounding.
closes #1051

fix: handle decimal point for spinbox #1051

---

ui/src/date_picker.tsx

* Fixes timezone bug when displaying the day in the Datepicker component
closes #1098

fix: correctly display selected day in datepicker #1098

---

py/examples/header.py
py/examples/nav.py
py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
ui/src/header.tsx
ui/src/index.scss
ui/src/layout.tsx
ui/src/nav.tsx
ui/src/persona.tsx
ui/src/theme.ts

```ts
/** Create a card containing a navigation pane. */
export interface State {
/** The navigation groups contained in this pane. */
items: NavGroup[]
/** The name of the active (highlighted) navigation item. */
value?: S
/** The card's title. */
title?: S
/** The card's subtitle. */
subtitle?: S
/** The icon, displayed to the left. **/
icon?: S
/** The icon's color. **/
icon_color?: S
/** The logo displayed at the top. **/
image?: S
/** The user avatar displayed at the top. Mutually exclusive with image, title and subtitle. **/
persona?: Component
/** Items that should be displayed at the bottom of the card if items are not empty, otherwise displayed under subtitle. */
secondary_items?: Component[]
/** Card background color. Defaults to 'card'. */
color?: 'card' | 'primary'
}
```
cc …

feat: Sidebar improvements

---

py/examples/facepile.py
py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
ui/src/facepile.test.tsx
ui/src/facepile.tsx

* If value is provided for facepile, submit that value when add button is clicked. If not, submit true
resolves #1133

feat: add value prop to facepile #1133

---

py/examples/choice_group_inline.py
py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
tools/intellij-plugin/src/main/resources/templates/wave-components.xml
tools/wavegen/wave-components.json
ui/src/choice_group.tsx
website/components/form/choice_group.md

feat: Add inline option for choice group #1145

---

ui/src/color_picker.tsx

* Visually indicate which color is currently selected on color picker

fix: Select color on swatch color picker #1099

---

website/docs/change-log.md

docs: Update changelog with 0.20 release

---

ui/src/table.tsx

Add Select and Deselect all functionality to filter menu

feat: Add select / deselect all to table filter menu #602

---

ui/src/table.tsx

fix: Dock footer to the bottom even if height is greater than total rows. #1248

---

ui/package-lock.json
ui/package.json
ui/src/plot.tsx

feat: Upgrade g2. Fix minor bugs along. #805

---

py/examples/header.py
ui/src/header.tsx
ui/src/index.scss
ui/src/nav.tsx
ui/src/theme.ts
website/widgets/content/header.md
website/widgets/content/navigation.md

This PR removes saturation for primary colored header/sidenav. Another option to go about this is [here](https://github.com/h2oai/wave/issues/1257#issuecomment-1047786415)
Closes #1257

fix: Remove header/sidebar primary color saturation. #1257

---

website/blog/2022-04-11-release.md

Really amazing blog @mturoci ! Did `0.21.0` for consistency with other places in our docs / blogs and added code-quotes once.

Small changes for release blog

---

py/examples/dropdown.py
ui/src/dropdown.tsx

Also removed the placeholder from the search box.
https://user-images.githubusercontent.com/15820796/163210499-418df6b4-9301-43fc-8715-cd0719fa0805.mov
closes #1349

fix: Add placeholder to dropdown with dialog

---

py/examples/combobox.py
py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
tools/intellij-plugin/src/main/resources/templates/wave-components.xml
tools/vscode-extension/component-snippets.json
ui/src/combobox.tsx

```ts
export interface Combobox {
...
/** True if this is a required field. */
required?: B
}
```
closes #1217

feat: Add required attribute to combobox

---

ui/src/table.test.tsx
ui/src/table.tsx

https://user-images.githubusercontent.com/23740173/162934246-aa0da8d0-6f7b-4231-9a24-cff6485eca45.mov
Closes #1314

feat: Display sorting icons only if sort is active

---

py/examples/combobox.py
py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
tools/intellij-plugin/src/main/resources/templates/wave-components.xml
tools/vscode-extension/component-snippets.json
ui/src/combobox.test.tsx
ui/src/combobox.tsx
website/widgets/form/combobox.md

https://user-images.githubusercontent.com/15820796/161720832-d5e65948-bc47-4fad-9dce-337bea2f2af0.mov

feat: Add multi select combobox

---

ui/src/message_bar.tsx
ui/src/notification_bar.tsx

Notification bar
Message bar inside form card
closes #1398

feat: reduce form Message Bar padding

---

py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
ui/src/notification_bar.test.tsx
ui/src/notification_bar.tsx
website/widgets/overlays/notification_bar.md

* Keep notification open if timeout is set to -1
* Close notification with buttons by default
https://user-images.githubusercontent.com/15820796/168084722-e568df17-f801-4dfb-8cfd-00b3ad766331.mov
closes #1366

feat: keep notification open if timeout is set to -1

---

website/blog/2022-05-31-release.md

updated blog to reflect R app support.

updated h2owave for R support description

---

web-ide/web_ide.py

Allows user to open the preview in the new browser tab.
https://user-images.githubusercontent.com/23740173/173298754-c81942f5-506d-43f1-b7a6-47ae2e3c2dae.mov

Feat: Open preview in new browser tab

---

web-ide/web_ide.js
web-ide/web_ide.py

https://user-images.githubusercontent.com/23740173/173614266-c173a5d6-dc1b-466a-b28b-c03c06006e1d.mov

Feat: View mode dropdown

---

auth.go

I found the new feature not worked in my project, after checking code, I fixed this issue, would you please help me review the change? thanks!

🐞 fix: using r.Host if post_logout_redirect_url not set

---

ui/src/file_upload.tsx

https://user-images.githubusercontent.com/23740173/177961714-fff107c7-8055-4683-9ae4-1a2d605e4262.mov
Closes #1505

Fix: Clear previous error when file with correct extension is uploaded

---

file_server.go

fix: Account for baseURL when deleting files (site.unload). #1557

---

cmd/wave/main.go
conf.go
server.go
website/docs/configuration.md

feat: Allow skipping Wave server TLS verification #1547

---

ui/src/app.tsx

feat: Add more detailed disconnect message. #1579

---

py/examples/table_column_alignment.py
py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
tools/intellij-plugin/src/main/resources/templates/wave-components.xml
tools/vscode-extension/component-snippets.json
ui/src/table.tsx
website/widgets/form/table.md

Closes https://github.com/h2oai/wave/issues/1659
- Added an option to the `ui.table` component to allow users to specify alignment per column.
- Alignment values could be one of ['left', 'center', 'right']
- Added new example `table_column_alignment.py` so that original `table.py` remains unchanged
- Added this new feature to `table.md`
- Ran `make generate` before raising PR

feat: align table column values

---

ui/src/table.tsx

fix: Add support for unicode in table export

---

website/docs/getting-started.md
website/src/pages/index.js

feat: Add github star count to Getting Started

---

py/README.md
website/docs/installation.mdx
website/docs/tutorial-hello.md

This PR fixes typos and updates the Conda install instructions.

[DOCS] Conda install

---

py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
tools/intellij-plugin/src/main/resources/templates/wave-components.xml
tools/vscode-extension/component-snippets.json
ui/src/image_annotator.test.tsx
ui/src/image_annotator.tsx
ui/src/image_annotator_polygon.ts
ui/src/image_annotator_rect.ts
website/widgets/form/image_annotator.md

Added:
* Cancel polygon drawing by hitting Escape key.
* Fixed minor bugs.
* Remove existing polygon point by right clicking.
* Trigger support.
* Allow constraining what shapes can be used for drawing.

feat: Label genie image annotator polygon feedback.

---

ui/src/parts/lightbox.tsx

This PR brings the refactor of image popup/lightbox component and also adds a pointer cursor on clickable areas.

feat: Image popup refactor

---

py/examples/link.py
py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
ui/src/link.test.tsx
ui/src/link.tsx
website/docs/files.md
website/widgets/form/link.md

feat: Make download attribute work more consistently. #999

---

py/examples/progress.py
py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
tools/intellij-plugin/src/main/resources/templates/wave-components.xml
tools/vscode-extension/component-snippets.json
ui/src/progress.tsx
website/widgets/form/progress.md

- Implemented the necessary changes in `progress.tsx`.
- Updated `progress.py` example.
- Updated `progress.md` docs.
Closes #1747

feat: Add spinner attribute to ui.progress #1747

---

ui/src/notification_bar.tsx

https://user-images.githubusercontent.com/23740173/214858284-d6bbddff-a40b-4e31-ba94-1c035b6134e2.mov
Closes #1764

fix: Make ui.notification_bar to overlay the ui.side_panel

---

ui/src/dropdown.test.tsx
ui/src/dropdown.tsx

fix: Disable Select/Deselect all buttons when ui.dropdown is disabled

---

py/examples/inline.py
py/h2o_wave/types.py
py/h2o_wave/ui.py
r/R/ui.R
tools/intellij-plugin/src/main/resources/templates/wave-components.xml
tools/vscode-extension/component-snippets.json
ui/package.json
ui/src/form.tsx
ui/src/message_bar.tsx
ui/src/section.tsx
website/widgets/form/inline.md
website/widgets/form/overview.md

feat: Add direction attribute to ui.inline. #1780

---

ui/src/dialog.tsx
ui/src/notification_bar.tsx
ui/src/side_panel.tsx
ui/src/time_picker.tsx

https://user-images.githubusercontent.com/23740173/219204873-44217148-b199-474a-baaa-30ef4fa9aa96.mov
https://user-images.githubusercontent.com/23740173/219204859-060bebcb-dd90-4e51-85f3-a13c2dafadfc.mov
Closes #1833
Closes #1847

feat: Make the popup of ui.time_picker visible over the side panel

---

py/h2o_wave/h2o_wave/core.py

Make fast file uploads work in cloud env as well.

chore: Account for absolute data_dir paths during file uploads.

---

py/h2o_wave/h2o_wave/server.py
website/docs/security.md

Sync ensure fresh token version - to be tested.

feat: Sync ensure fresh token.

---

ui/src/menu.test.tsx
ui/src/menu.tsx

fix: Do not open menu on Esc key press #1866

---

ui/src/table.tsx
ui/src/tag_table_cell_type.tsx

https://user-images.githubusercontent.com/23740173/232830137-41d48075-9e95-4ce1-bef9-d6fda0954244.mov
Closes #1917

fix: Display tags in wrapped cells correctly #1917

---

py/apps/dashboard/app.toml
py/apps/theme-generator/app.toml
py/apps/tour/app.toml
university/app.toml

feat: Pin the python runtime version for Appstore Wave apps #1873

---

py/examples/tour.js
py/examples/tour.py

This change enhances the Wave **tour app** experience with the support for smaller screens.
https://github.com/h2oai/wave/assets/23740173/7a528c04-a1fd-4009-82ee-cb81337ed736

feat: Make tour responsive

---

broker.go
client.go
website/docs/routing.md

Required by #1979 as it spawns a new Wave app process per client and needs to perform proper clean up.

feat: Notify about client disconnect.

---

py/examples/tour.py

~~TODO: Stop app process on client disconnect.~~ Done.

feat: Multiuser Tour.

---

py/h2o_lightwave/h2o_lightwave/types.py
py/h2o_lightwave/h2o_lightwave/ui.py
py/h2o_wave/h2o_wave/types.py
py/h2o_wave/h2o_wave/ui.py
r/R/ui.R
ui/src/table.tsx
ui/src/tooltip.tsx
website/widgets/form/table.md

https://github.com/h2oai/wave/assets/23740173/efec4285-74ea-448d-9d42-15e5b819894c
Closes #2013

feat: Allow ui.table to fill the remaining card height

---

py/apps/theme-generator/requirements.txt
py/apps/tour/requirements.txt
py/examples/requirements.txt
py/examples/theme_generator.py

https://github.com/h2oai/wave/assets/23740173/0094afcb-448d-47b7-8dd3-98273e6c3ba2

feat: Make theme generator responsive

---

.github/workflows/release-wave-nightly.yml
tools/intellij-plugin/build.gradle.kts

Bump Intellij gradle plugin version to make the build pass.

chore: Bump IntelliJ gradle plugin to make the build process pass.

---

university/h2o_wave_university/university.py

https://github.com/h2oai/wave/assets/23740173/aebfac8d-d011-44e0-b259-3b27a9986a18

feat: Make wave university responsive

---

.github/CONTRIBUTING.md
.github/workflows/snyk-scan.yml
README.md
py/apps/dashboard/README.md
py/apps/dashboard/about.md
py/apps/theme-generator/README.md
py/apps/tour/README.md
py/apps/tour/about.md
py/examples/layout_responsive.py
py/h2o_lightwave/README.md
university/README.md
website/blog/2022-05-31-release.md
website/blog/2022-09-12-release.md
website/docs/contributing.md
website/docs/layout.md
website/docs/security.md
website/docs/wavedb.md
website/docusaurus.config.js
website/widgets/content/image.md
website/widgets/form/image.md
website/widgets/stat/table_stat.md

chore: SOC2 prerequisite - Rename master to main.

chore: Rename master to main prep.

---

py/h2o_wave/h2o_wave/cli.py

fix: Run waved process in a separate process group on Windows so that wave run works on modern uvicorn. #2074

---

ui/src/date_picker.test.tsx
ui/src/date_picker.tsx

fix: Allow dynamic value change for date picker #1154

---

ui/src/toggle.test.tsx
ui/src/toggle.tsx

fix: Allow dynamic value change for toggle #1154

---

ui/src/slider.test.tsx
ui/src/slider.tsx

fix: Allow dynamic value change for slider #1154

---

ui/src/checklist.test.tsx
ui/src/checklist.tsx

fix: Allow dynamic value change for checklist #1154

---

ui/src/color_picker.test.tsx
ui/src/color_picker.tsx

fix: Allow dynamic value change for color picker #1154

---

ui/src/tab.test.tsx
ui/src/tab.tsx
ui/src/ui.ts

fix: Allow dynamic value change for tab card #1154

---

ui/src/nav.test.tsx
ui/src/nav.tsx

fix: Allow dynamic value change for nav card #1154

---

.github/workflows/release-wave-nightly.yml
e2e/Makefile
e2e/requirements.txt
e2e/test_by_name_updates.py
e2e/test_card_interaction.py
e2e/test_oidc.py

Make e2e tests more stable, add py3.11 to testing matrix, fix macos docker setup.

ci: Stabilize nightly job.

---

py/h2o_wave/h2o_wave/cli.py
py/h2o_wave/h2o_wave/share.py

Change wave share client protocol due to server rewrite.

refactor: Change wave share client protocol.

---

ui/src/button.tsx
website/widgets/form/button.md

fix: Apply primary button styles for icon button #2121

---

py/Makefile
setup.ps1

Fixed bug in metadata where \n isn't recognized as a new line. 

---

ui/src/plot.tsx

@marek-mihok - can you make a code review and a thorough QA to check if everything works as expected?

feat: Format dates inside plot tooltips properly.

---

py/examples/table.py
ui/src/table.test.tsx
ui/src/table.tsx

@marek-mihok - can you make a code review and a thorough QA to check if everything works as expected?

chore: Prevent internal table groups regression. #2103

---

py/h2o_lightwave/h2o_lightwave/types.py
py/h2o_lightwave/h2o_lightwave/ui.py
py/h2o_wave/h2o_wave/types.py
py/h2o_wave/h2o_wave/ui.py
r/R/ui.R
tools/intellij-plugin/src/main/resources/templates/wave-components.xml
tools/vscode-extension/component-snippets.json
ui/src/stats.tsx
ui/src/tall_stats.tsx

___
https://github.com/h2oai/wave/assets/23740173/591f0027-f36c-4590-94a5-e14ccd74a740
Closes #2197

feat: Add name attribute to ui.stats #2197

---

app.go
auth.go
broker.go
server.go

A tmp fix for #2185. Still did not manage to repro thus couldn't find the exact cause for why is the `token` nil. In theory, it's fine since this happens during logout anyway, but I would be happier if we managed to resolve the real cause so that there are no surprises in future.

fix: Ignore nil token err.

---

ui/src/image_annotator.test.tsx
ui/src/image_annotator.tsx
ui/src/image_annotator_polygon.ts
ui/src/image_annotator_rect.ts

___
This PR brings the following enhancements:
- Both points and aux points match the tag colors.
- Line thickness and point size does not change when zooming.
https://github.com/h2oai/wave/assets/23740173/096ac635-955d-4b00-bec0-b029b5d6f077
Closes #1860
Closes #1862

feat: Image annotation shapes improvements #1860

---

ui/src/index.scss
ui/src/markdown.css

____
This PR sets the primary color for all links globally.
Closes #2281

feat: Make links use primary color #2281

---

setup.ps1

___
Fixes failing nightly py tests on windows after #2286.

fix: Add urllib3 to setup.ps1

---

website/docs/pages.md

___
All the other occurrences of the `q.page.drop()` within the project are correct.
Closes #2319

docs: Remove await keyword for q.page.drop() #2319

---

py/h2o_lightwave/h2o_lightwave/server.py

Update maxsplit on websocket message #2344

---

conf.go
socket.go
website/docs/configuration.md

feat: Allow `*` in allowed_origins. #2370

---

py/h2o_wave/h2o_wave/core.py
py/h2o_wave/h2o_wave/server.py
website/docs/configuration.md

feat: Configurable app timeouts.

---

py/examples/checklist.py
ui/src/checklist.test.tsx
ui/src/checklist.tsx

fix: add exclusion for disabled choices in checklist select and deselect all changes  + tests closes #2427

---

.github/workflows/wave-bundle-docker-build-publish.yaml

feat: Migrated the wave workflows to use H2O ECR from ROOT Account

---

.github/workflows/release-wave-nightly.yml
.github/workflows/release-wave.yml
.github/workflows/release-wavedb.yml
go.mod

Security: Update Go to 1.23.0
