ide/package-lock.json, package-lock.json, test/package-lock.json
If merged the issue with an `ini` package will be resolved:
```The ini npm package before version 1.3.6 has a Prototype Pollution vulnerability.```
I used `npm audit` to see what's going on and followed the advices printed out.
=> Update ini version in package lock files

ui/src/page.tsx
* AddListener Safari - https://github.com/mdn/sprints/issues/858
* Also had to specify a min-height in addition to height since Safari Flexbox implementation differs as well.
We can also use a addListener only in case addEventListener is not available, but I checked and this works in other browsers as well so didn't want to pollute the code.
Closes #382
=> Safari quirks

client.go, py/h2o_wave/server.py, socket.go
If PR merged, the OIDC `refresh` token will be propagated to python client the same way as other properties. This change is needed because of API for DAI and MLops which require `refresh` token to be able to handle long running tasks.
The token is accessible in `q.auth.refresh_token`.
Closes #365
=> Forward refresh token to python client

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, website/docs/contributing.md
* updated _CODE OF CONDUCT_ to the Ruby one @lo5 added
* Merged CONTRIBUTING.md with contribution page - left the social aspect of contribution page (+ fixed a few typos) and added dev setup to get you up and running from original CONTRIBUTING.md
Wondering whether we should delete `DEV.md` and link to newly merged `CONTRIBUTING.md` instead.
Closes #400
=> docs: unify contribution guide #400

.markdownlint.json, README.md
Added a few shields to readme that might be worth. Looking for opinions.
vs
Further possible Readme improvements - do not use links directly, but via `[](url)` to make it consistent.
Note that I golang and nodejs versions are hardcoded and simply taken from my machine, feel free to point out if we support lower versions as well.
=> docs: add shields to main readme

py/examples/tour.py
Windows do not support SelectorEventLoop. To support tour in all the platforms, replaced asyncio.create_subprocess_exec() with python subprocess. Fixes: https://github.com/h2oai/wave/issues/397
Verified on: Windows 10. python 3.7.9 and python 3.8.6, python 3.9.1, MacOS Catalina 10.15.5
=> Replace asyncio.create_subprocess_exec() with python subprocess for tour

py/h2o_wave/server.py
Wave CLI dynamically generates host:port combinations to be paased to uvicorn and update the ENV with that address(H2O_WAVE_APP_ADDRESS). However wave server doesn't inter the updated value when registering an application. This PR fixes that issue.  Fixes: https://github.com/h2oai/wave/issues/391.
=> Infer correct app address from ENV

website/docusaurus.config.js, website/src/css/custom.css
fixes #309
- Using Algolia with Docusaurus2 is surprisingly simple. [Link to Docusaurus' config](https://github.com/facebook/docusaurus/blob/2791ccc4cfb6581a33e36c6d018d098daf403ce4/website/docusaurus.config.js#L268)
- By default, the `dark-theme` readability in the search box isn't good. Used the defaults from [Docusaurus docs](https://v2.docusaurus.io/docs/search#styling-your-algolia-search) and improved it. Tried to follow the [Infima](https://v2.docusaurus.io/docs/styling-layout#styling-your-site-with-infima) design pattern.
https://user-images.githubusercontent.com/16831326/103168260-6eafd780-47e6-11eb-9794-2b2c151b5c67.mp4
=> feat: searchable documentation #309

py/h2o_wave/__init__.py, website/sidebars.js
=> fix: API section of the docs has mismatched sidebar and index items

py/demo/dashboard_grey.py, ui/src/parts/microarea.tsx, ui/src/parts/microbars.tsx, ui/src/parts/progress_arc.tsx, ui/src/plot.tsx, ui/src/small_series_stat.tsx, ui/src/tall_series_stat.tsx
* Use absolute positioning (to avoid normal document flow) to avoid weird flexbox behavior with inline SVG - probably due to scalability capabilities.
* Fix some flexbox browser quirks - flex child didn't take full height on all major browsers - tested with Chrome, Safari, Firefox, Edge.
* Recompute svgs on `resize` event.
* Fixed grey dashboard as commented in issue.
Closes #473
=> Flex layout fixes

ui/src/dialog.test.tsx, ui/src/dialog.tsx
Fluent's dialog type `close` requires user to handle closing manually instead of providing such functionality out of the box.
Closes #478
=> Fix closable dialog

py/conda/meta.yaml
Explicitly set Conda package name as h2o-wave
=> fix: explicitly set conda package name

py/examples/plot_dataframe.py, py/examples/tour.conf
Addresses question from discourse with a new example that shows how you can use `df.values.tolist()` with Wave's `data` class to easily visualize data from a dataframe. I included two examples in a single file which should help people get started: one with visualizing ALL the data and one where you are aggregting in pandas and visualizing some trend. 
Hopefully this + the more advanced plot examples using Faker will help pandas folks get started. 
This would be the first example using `data(fields, rows)` vs. `data(fields, size)`
=> Add new plotting example(s) directly from dataframe

test/cypress.py
fix test/cypress.py runner broken by #287
```
Traceback (most recent call last):
File "test/cypress.py", line 194, in <module>
main()
File "test/cypress.py", line 190, in main
run_app_with_test(**vars(args))
File "test/cypress.py", line 100, in run_app_with_test
do_run()
File "test/cypress.py", line 75, in do_run
sleep_time=delay,
File "test/cypress.py", line 30, in __enter__
env=self.env,
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
restore_signals, start_new_session)
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1453, in _execute_child
restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
=> bugfix: fix cypress test runner

ui/src/parts/progress_arc.tsx
`height: 100%` is not working for flex parent with `flex-grow: 1`. Had to use absolute positioning instead.
Closes #520
=> Fix ProgressArc in Safari

py/examples/dashboard.py, ui/src/frame.tsx
The core problem is that Safari's `height: 100%` implementation differs from Chrome/FF. It used default height `150px` instead. The iframe wrapper correctly takes up all the space via `flex-grow: 1`, but iframe is still not capable of filling it corectly.
None of the workarounds found could solve this, so I went for absolute positioning.
Discussion: This fix affects `frame_card` only as it works with dynamic height (the only way to control height is to change card's height). I believe it is enough since form frames have the ability to control height manually with default to `150px`. if not, we can exchange the `150px` height default for `flex-grow:1` and absolute positioning in the same way like `frame_card`.
Closes #519
=> Safari iframe fix

ui/src/vega.tsx
Needs discussion:
As discussed with @goldentom42, there are basically two ways for manipulating card size in Wave:
1. Card level - specified it in layout definition.
2. Card content - card size is based on its content.
#543 can be resolved easily by (1).
Vega allows controlling its dimensions via [spec](https://vega.github.io/vega-lite/docs/size.html). Which is (2) approach. This PR introduces ability for handling `height` defined in spec, but I don't think it makes sense for `width` as well, since `vega_card` has only plot as content and you always want to stretch it to the full of the container (see images below)
**Stretched**
**Static width in vega spec**
My opinion is that we should follow general Wave philosophy and treat everything layout related in `layouts` (for flex layout) or …
=> feat: allow using height in vega spec #543

ui/src/small_series_stat.tsx, ui/src/wide_gauge_stat.tsx
Changes 15px padding to 8px for top/bottom for small_series_stat and wide_gauge_stat cards in order to remove the overflow.
=> fix: remove overflow for stat cards by reducing top/bottom card padding

ui/package-lock.json
Resolves warning during ui build.
Run `npm i` after pulling this change.
=> chore: update caniuse-lite to remove warning during ui build

website/docs/security.md
If PR merged, the security page of Wave docs will be updated of `access token` lifespan info.
=> docs: Update security page of access token info

py/setup.py
If PR merged, the first version of ML API will be available in Wave. ML API is completely separated and will be installable by:
```sh
pip install h2o-wave[ml]
```
=> feat: Add ML API as a pip option

ui/src/table.tsx
Also added a bit of a spacing between GroupBy / Search bar and table itself.
Closes #560
=> fix: adjust table footer color to card color #560

ui/src/form.tsx
Needs more testing.
Closes #563
=> fix: remove displaying form items in flex column due to Safari #563

.github/workflows/publish-docs.yml
Fix for permission denied to commit to protected branch issue in Github actions pipeline.
=> fix: Set git PAS to publish docs workflow

ui/src/parts/microarea.tsx, ui/src/parts/microbars.tsx, ui/src/parts/progress_arc.tsx, ui/src/plot.tsx
The problem was that React runs its `componentDidMount` lifecycle hook when browser Layout phase is not finished yet, giving us incorrect dimensions required for plot calculations:
This is the state of UI when our React hooks run. Safari will eventually catch up, but by the time, we already have incorrect dimensions in place. Flexbox Layout is not done yet, each component is displayed in its own row (width 1200px) and calculates the rest with this dimension, resulting in odd-looking plots as described in the issue.
This bug was especially hard to debug since it is not reproducible with Safari devtools open for some reason.
One solution that worked for unknown reason was to add a fake timeout on initial loading phase (spinner). It seemed like Safari could finish all the work needed on its …
=> fix: add post init dimensions check to plots due to Safari event loop behavior #516

ui/src/table.tsx
https://user-images.githubusercontent.com/64769322/111309172-e0682680-865b-11eb-827f-4519dafba540.mov
* Prevented _Rows x of y_ text from wrapping when screen size reduced.
* Added enough space for Download & Reset toolbar.
Closes #609
=> Fix table footer overflow menu

.github/CODE_OF_CONDUCT.md, README.md, website/docusaurus.config.js
* Changed CoC.
* Added contributor-covenant badge to readme.
* Added CoC entry to docs footer under `Community`.
* Added **prithvi@h2o.ai** as a contact person (can be a subject to change, just need to know who to put there).
Closes #641
=> chore: switch CoC to contributor-covenant #641

ui/src/plot.tsx
It seems like this is a bug from the plotting lib. There are 2 possible solutions:
* Since `zoom-view` is not working on Firefox, one option is to remove it so that we get consistent behavior across all the browsers.
* If we however don't want to do that, this PR stops further event propagation thus page scroll does not happen. This behavior is turned off for Firefox as it makes no sense to forbid the page scroll and not provide zoom-view as well.
Fix in action:
https://user-images.githubusercontent.com/64769322/112176610-8980c500-8bf8-11eb-8b3b-ab5f0219aa0d.mov1
Closes #659
=> Stop scroll propagation for plots

ui/public/index.html
This PR allows auth cookies for `manifest.json`. The question is, whether deleting the manifest completely isn't better option since it serves as metadata for PWAs, which we currently don't support.
Closes h2oai/h2o-ai-cloud#798
=> fix: allow auth cookies for manifest.json #h2oai/h2o-ai-cloud#798

py/examples/plot_matplotlib.py, py/examples/plot_plotly.py
=> docs: use explicit instead of truthy throughout the examples #168

auth.go, client.go, socket.go
Refreshes access token when handling websocket messages. If an error occurs, it's ignored (maybe we want to change this @lo5? )
=> feat: refresh access token when handling websocket messages.

py/Makefile, website/docs/wave-ml.md, website/sidebars.js
If PR is merged, `Wave ML` guide will be added to the docs. I included a description, current API overview, and function prototypes. We can also add a Wine tutorial to the `Getting Started` section if desired.
Resolves #683
=> Add Wave ML guide to docs

py/Makefile
I dropped `datatable` package entirely from *Wave ML* and released under `v0.5.0`. Also changed build target so *Wave ML* repo will be downloaded every time the target is invoked.
Resolve #759
=> fix: update py/Makefile target and version #759

.github/workflows/release.yml
Fixes release CI workflow.
This PR updates `npm` to version `7.11.1` in order to be able to work with `packge-lock` file v2.
Each job can run on different machine so npm has to be updated for both. I am not sure why we even have 2 workflows anyway. I would put unit tests as a separate step within `release` workflow, which would be cleaner and wouldn't require 2 npm installs for `ui` folder.
=> Fix CI by updating npm

py/Makefile
If PR merged, the warning about using legacy install for Wave ML will vanish:
```
Using legacy 'setup.py install' for h2o-wave-ml, since package 'wheel' is not installed.
```
Wheel is needed if installing package locally by `setup.py` (`pip install .`). The message will not pop up if installed from indexed package (`pip install h2o-wave-ml`).
=> Fix legacy warning for Wave ML setup

py/examples/tour.py
https://user-images.githubusercontent.com/64769322/115402327-9db1e500-a1eb-11eb-8e89-aa13883414fa.mov
Open questions:
* Do we want to make the tour even mobile friendly (to show flex layout capabilities) or is flex desktop (current state) enough?
Possible improvements:
* Split nav menu into subgroups (form / plots etc.) to make it easier for user when searching something.
* Dark mode?
* Implement global search to quickly go to the example that user wants. This could be achieved by using either `picker` (not so great) or by #303 (better).
* Clean up all the examples and make them use only the minimum necessary card space (box) so that it doesn't cause overflow within tour iframe even though content is short.
* Distant future - integrate our online IDE and make the tour examples editable …
=> Switch Tour to flex layout

website/blog/2021-04-28-release.md, website/docusaurus.config.js, website/static/fix-location.js
If PR merged, two changes will be introduced to the repo:
- The link from the blog will be changed to a relative one so jump from the blog to API should not end up with a trailing slash.
- The script `fix-location.js` will be introduced to prevent a trailing slash.
This is the expected flow of the events:
1. User loads the page on e.g. `https://wave.h2o.ai/docs/api/index`
2. Web server responds with 302 (`Moved Temporarily`)
3. User loads the redirected page `https://wave.h2o.ai/docs/api/index/`
4. Script `fix-location.js` executes and fixes the URL to `https://wave.h2o.ai/docs/api/index`
5. React resolves relative links using `https://wave.h2o.ai/docs/api/index`.
I haven't tested this on AWS but I have partially tested it with several tools and it should work.
- I was trying to modify …
=> Auto correct website URL

py/Makefile, website/sidebars.js
A new version of Wave ML is out. This PR updates the docs.
=> Update Wave ML docs to 0.6.0

py/Makefile, website/sidebars.js
A new version of Wave ML is out. The PR updates the docs.
=> Update Wave ML docs to 0.7.0

website/static/fix-location.js
This is a continuation of #783. @vopani realized the hashes in docs are mishandled, i.e.: `https://wave.h2o.ai/docs/api/h2o_wave_ml/ml/#build_model` redirects to `https://wave.h2o.ai/docs/api/h2o_wave_ml/ml`.
PR will preserve hash.
- This fix was tested directly on `https://wave.h2o.ai/`. Actually, the page has fix already present.
=> Preserve hash in docs url

py/Makefile
A new version of Wave ML is out. The PR updates the docs.
=> Update Wave ML docs to 0.8.0

py/examples/table.py, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, ui/src/table.test.tsx, ui/src/table.tsx
Primary column prioritized `Fluent.Link`. This PR fixes this by prioritizing `cell_type` cols first and then wrapping col content in link if applicable. This also fixed unknown bug - if `time` col would be specified as first, it wouldn't be formatted properly - added unit test for it.
Needs discussion: 
Current logic - if first col is `cell_type` don't add link functionality (not clickable to emit `q.args.table_name`)
Alternative - wrap also `cell_type` within `Flluent.Link` which will make e.g. progress arc clickable - not sure if makes sense though.
Nits: Changed excessive example box height to avoid scrollbars. Updated `link` docstring.
Closes #890
=> fix: Primary table column

py/examples/routing_predicates.py
Fix a small typo in [Wave docs](https://wave.h2o.ai/docs/examples/routing-predicates)
=> fix: Fix typo in docs

py/sync_examples.py
There are 2 options we can deal with it:
* Completely remove the edit option via the main config removing `editUrl`.
* Remove the option for particular (generated) pages only using `custom_edit_url: null` in markdown frontmatter.
This PR goes with the second options, but can be changed ofc.
Pages without edit option: all examples, tags and gallery page. Let me know if there are any others that should be included as well.
Closes #928
=> docs: Remove 'Edit this page' links for generated content #928

auth.go, cmd/wave/main.go, conf.go, website/docs/security.md
If PR merged, the default scopes for OAuth request will be updated of `profile` and a new command-line argument `-oidc-scopes` will be introduced.
The `profile` scope is added so `openid` and `profile` are now default. This change will ensure the `preferred_username` will be available in ID token making `q.auth.username` not to be empty while using e.g. *Okta*. Note that the `profile` scope is listed as a standard scope for OpenID and should always be available.
The `-oidc-scopes` is added so if `openid` and `profile` are not enough, it's possible to list values that override the defaults. Values are comma-separated:
```bash
./waved -oidc-scopes openid,profile,offline_access
```
I was considering adding `offline_access` to default scopes as well to enable the `q.auth.refresh_token` in …
=> feat: Update default Scopes and add `-oidc-scopes` cmd argument

py/examples/ml_dai.py, py/examples/ml_dai_autodoc.py, py/examples/ml_dai_categorical.py, py/examples/ml_dai_instances.py, py/examples/ml_dai_parameters.py, py/examples/ml_dai_save.py, py/examples/tour.conf
This PR adds examples of using WaveML with DAI.
Closes h2oai/wave-ml#43
Comments:
* These only work on H2O AI Hybrid Cloud. If run locally, it displays a sign-up message.
* The default setup takes about a minute to run and the outputs are mainly links to DAI and MLOps.
* It requires some `toml` changes to publish on cloud, will ensure those get updated.
=> WaveML DAI examples

ui/src/tab.tsx
The overflow was caused by [overflow auto](https://github.com/h2oai/wave/blob/5c2e4549cab38f85948f12b4cabf4afc91693de6/ui/src/layout.tsx#L164) on our side cascading down to `Fluent.Pivot` which didn't account for extra 2px height of pseudo `::before` in addition to existing `44px` pivot button `height` and `line-height` of its text. Increasing container `min-height` by 2px fixes the issue.
Also the reason this happens with flex layout only is that it uses intrinsic element height as opposed to strictly set calculated height of the old grid. 
Closes #904
=> fix: Increase tab card min height to prevent overflow. #904

py/examples/markdown_submit_text.py, py/examples/tour.conf, ui/src/app.tsx, ui/src/markdown.test.tsx, ui/src/markdown.tsx
This PR intercepts `markdown-it` text rendering process and adds an `onclick` listener if the href attribute is prefixed with `?`. The listener code is inlined, otherwise it would require a globally available function. Apart from the fact that globals in general are not a good idea, it would be of no use since webpack changes function names during prod build, so the strings would not match either way.
This solution proposes use of custom events, both dispatched and listened on `window` object.
Closes #293
=> feat: allow submitting text phrases within markdown

py/examples/link.py, ui/src/link.test.tsx, ui/src/link.tsx
The only solution that I managed to get working so far - perform download in a new tab so that current tab is not touched.
Alternatives tried:
* Using JS to trigger download, but unfortunately it seems like this is a browser-level issue so it doesn't matter what triggered the download.
Closes #899
=> fix: Download files in new tab to prevent FF dropping WS connection. #899

ui/src/app.tsx
If PR merged, blocking overlay will be updated of css solution.
The original solution worked but had opacity transition to non-blocking overlay as well. i.e.: if no blocking state on server happened in 2s+, user would have experienced the same - correct transition.
This PR separates classes and prevents transition mixing.
Continuation of #17 and #236
=> Update blocking overlay for css only solution

ui/src/form.tsx, ui/src/range_slider.tsx, ui/src/section.tsx, ui/src/slider.tsx
The sliders were cramped within `ui.inline` because there was no default width specified originally. This PR sets it for 100% which doesn't change anything if slider specified as a form child and takes up available space for inline. This seems reasonable for me since short sliders (not wide enough) are harder to use because of smaller dragging area. Another possiblity is to specify default min width or exposing width attr. 100% width solution feels the best though.
Fixed with 100% width:
Possible improvements: Make our range slider UX the same as Fluent one, something like:
Closes #582
=> fix: stretch slider for available space #582

py/examples/meta_side_panel.py, py/examples/tour.conf, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, ui/src/app.tsx, ui/src/file_upload.test.tsx, ui/src/meta.tsx, ui/src/side_panel.test.tsx, ui/src/side_panel.tsx, ui/src/table.tsx
Current demo:
https://user-images.githubusercontent.com/64769322/129548308-83eaab7d-58d5-4855-86f5-d300d2d5f3f3.mov
@lo5 
* I added `width` prop as well which I think might be handy - same as dialog.
* Added support for `q.events` on close - same as dialog.
* Needs discussion: It might be a good idea to introduce a `title` prop as well.
@sandruparo 
* As discussed, the designs need more work on colors. They are currently hardcoded and need to be themable instead.
* Current implementation doesn't use any offsets (top, right, bottom). The proposed design has them, but these seem like random values (top 223px, right 50px, bottom 244px). There are 2 options we have here:
1. Make the offset fixed - what is presented in the proposed design, but with reasonable values.
2. Use percentage value. …
=> feat: Side panel. #898

py/examples/persona.py, py/examples/tour.conf, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, ui/src/form.tsx, ui/src/persona.test.tsx, ui/src/persona.tsx
Demo:
https://user-images.githubusercontent.com/64769322/132238224-6aa37209-c773-4710-bfe9-1029064f7352.mov
In addition to the [proposed API](https://github.com/h2oai/wave/issues/970#issuecomment-909345128), I have also added 
```ts
/** Initials background color (CSS-compatible string). */
initials_color?: S
```
for color control over background.
changed `size` type to `'xl' | 'l' | 'm' | 's' | 'xs'` in order to avoid using Fluent types directly.
If `name` is specified, the whole component becomes clickable, supporting hash routing as well.
Closes #970
=> feat: Persona form component. #970

py/demo/dashboard_red.py, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, ui/src/flex.tsx, ui/src/form.tsx, ui/src/page.tsx, ui/src/section.tsx, ui/src/theme.ts
@lo5 API for review:
`ui.inline.justify` changed from `'start' | 'end'` to `'start' | 'end' | 'center' | 'between' | 'around'`.
Closes #534
=> feat: Introduce more values to ui.inline justify. #534

py/setup.py
I ran into the following error when building the website locally (OS X), I'm not sure if we expect non-existent variables to through errors, but using the default setting worked for me rather than relying on the `or`:
> Obtaining file:///Users/mtanco/Desktop/wave/py
ERROR: Command errored out with exit status 1:
command: /Users/mtanco/Desktop/wave/py/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/mtanco/Desktop/wave/py/setup.py'"'"'; __file__='"'"'/Users/mtanco/Desktop/wave/py/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' …
=> Fix failure of missing OS environmental variable in setup.

py/examples/meta_theme.py, py/examples/theme_generator.py, py/examples/tour.conf, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, ui/src/app.tsx, ui/src/color_picker.tsx, ui/src/meta.tsx, ui/src/theme.ts
This PR provides a way to easily generate color theme for a Wave app.
Custom theme specification:
```py
ui.meta_card(theme='<custom-theme-name>', themes=[ui.theme(name'<custom-theme-name>', text='\#000', card='\#fff', page=\'#e2e2e2', primary='\#000'])
```
Generator app is provided as a wave app, currently part of `Tour`, but can be distributed as separate app as well, same as `Dashboard demo`.
https://user-images.githubusercontent.com/64769322/110339226-34ee1f00-8028-11eb-9348-c2fc0b640e75.mov
Blocked by #150 - to provide smooth dragging experience like in Demo above ^^
Minor additions:
* Picker uses Fluent label to be conssistent with Dropdown or Datepicker components.
* Color picker has 2 new attrs - `alpha` to forbid choosing transparency and `inline` that shows color picker in a …
=> User defined themes

py/examples/tour.conf, py/examples/wide_plot.py, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, ui/src/cards.tsx, ui/src/plot.tsx, ui/src/wide_plot.test.tsx, ui/src/wide_plot.tsx
```ts
/** Create a wide plot card displaying a title, caption and a plot. */
interface State {
/** The card's title. */
title: S
/** The card's caption, displayed below the title. */
caption: S
/** The card's plot. */
plot: Plot
/** The card's plot data. */
data: Rec
}
```
possible to also add `events` if needed.
* What is the preferred text container width? I went with `200px` and let the plot take the rest of the space. We can also go for percentual ratio or something else.
* The space between text and plot seems to be too small (`8px` as per design)
Closes #1030
=> feat: WidePlotCard. #1030

py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, ui/src/tall_info.test.tsx, ui/src/tall_info.tsx, ui/src/wide_info.test.tsx, ui/src/wide_info.tsx
=> fix: make tall / wide info cards clickable based on name parameter #1117

ui/src/index.scss
Using colors: `--card8`, `--text0`, and `--text2`
Tested on MacOS.
resolves #1120
=> feat: set theme to scrollbar #1120

py/examples/dropdown.py, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, ui/src/dropdown.test.tsx, ui/src/dropdown.tsx, website/components/form/dropdown.md
* Define when dialog should be displayed. If not provided, display only when choices > 100
API: `dialog?: 'auto' <- (default) | 'always' | 'never'`
resolves #1116
=> feat: Add dialog prop to dropdown #1116

py/examples/tour.conf, py/examples/wide_article_preview.py, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/wavegen/wave-components.json, ui/src/cards.tsx, ui/src/wide_article_preview.test.tsx, ui/src/wide_article_preview.tsx, website/components/content/article.md
Default
H2O-dark
Neon
Proposed API: 
```ts
/** Create a wide article preview card displaying a persona, image, title, caption, and optional buttons. */
export interface State {
/** The card's user avatar, 'size' prop is restricted to 'xs'. */
persona: Component
/** The card’s image displayed on the left-hand side. */
image: S
/** The card's title on the righ-hand side */
title: S
/** An identifying name for this card. Makes the card clickable, similar to a button. */
name?: S
/** The card's auxiliary text, displayed on the right-hand side of the header. */
aux_value?: S
/** The card's caption, displayed bellow the title on the right-hand side. */
caption?: S
/** The card's buttons, displayed at the bottom-right corner. */
items?: Component[]
}
```
=> feat: add Wide Article Preview component #1132

.github/CONTRIBUTING.md
In Getting started section of Development setup in CONTRIBUTING.md there is a missing `run` keyword in a command running example tour. 
🔴**Wrong:** `cd py && ./venv/bin/wave examples.tour`
🟢**Correct:** `cd py && ./venv/bin/wave run examples.tour`
=> docs: Fix missing keyword in run command

py/examples/textbox.py, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/showcase/showcase.py, tools/wavegen/wave-components.json, ui/src/textbox.tsx, website/components/form/textbox.md
This PR introduces [requested feature](https://github.com/h2oai/wave/issues/606) to have option to disable spell checking in text input field.
See the screenshot below:
Closes #606
=> feat: Add ability to turn off spellcheck for textbox #606

py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/wavegen/wave-components.json, ui/src/dialog.test.tsx, ui/src/dialog.tsx, ui/src/side_panel.test.tsx, ui/src/side_panel.tsx
This PR addresses issue #1093  that user cannot allow side panel to be blocking.
The issue is resolved by adding `blocking` property to side panel (see examples).
**Examples:**
- `blocking=False` (default)
https://user-images.githubusercontent.com/23740173/149329423-6e639d94-c908-4ee5-b8c8-fed3d47ae230.mov
- `blocking=True`
https://user-images.githubusercontent.com/23740173/149329460-6728331e-8d20-4265-96ea-9533d0499f25.mov
The changes were made also to [dialog](https://github.com/h2oai/wave/blob/master/ui/src/dialog.tsx) where already existing `blocking` property now matches the same behaviour as on side panel examples above.
Closes issue #1093
=> Allow side panel to be blocking

website/widgets/overview.md
=> Tiny doc update - missing ')'

py/h2o_wave/cli.py
The Python code was expecting an integer in H2O_WAVE_LISTEN while the
Golang side was expecting :#####.  Fix this by updating the Python side
to parse the string version.
Fixes #1220.
=> Fix changing the default wave server port using env var

py/examples/nav.py, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/wavegen/wave-components.json, ui/src/nav.tsx
This PR introduces optional `tooltip` attribute to `nav_item`, which is displayed as a tooltip when user hovers over the nav item.
https://user-images.githubusercontent.com/23740173/150335269-732618c6-5e84-4f60-8970-c4e4a85b99a3.mov
Closes #692
=> feat: Add title attribute to NavItem to show as a tooltip #692

py/examples/message_bar.py, py/examples/meta_notification_bar.py, py/examples/tour.conf, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/vscode-extension/component-snippets.json, ui/src/app.tsx, ui/src/message_bar.tsx, ui/src/meta.tsx, ui/src/notification_bar.test.tsx, ui/src/notification_bar.tsx, website/widgets/form/message_bar.md
https://github.com/h2oai/wave/issues/1007#issuecomment-929074383
Working in Chrome / Safari / FF.
Unified `ui.message_bar` styling to match the `notification_bar` + added support for buttons to keep consistency
```ts
/**
* Create a notification bar.
*
* A notification bar is an area at the edge of a primary view that displays relevant status information.
* You can use a notification bar to tell the user about a result of an action, e.g. "Data has been successfully saved".
*/
export interface NotificationBar {
/** The text displayed on the notification bar. */
text: S
/** The icon and color of the notification bar. Defaults to 'info'. */
type?: 'info' | 'error' | 'warning' | 'success' | 'danger' | 'blocked'
/** When should the notification bar disappear in seconds. Defaults to 5. */ …
```
=> feat: Notification bar.

ui/src/table.tsx
Fixes the click handler for Chevron Down icon on Table component. Didn't spot the same incorrect behavior on other icons.
=> fix: make table filter icon clickable

ui/src/table.tsx
Prevent user from opening contextual menu on non-filterable column headers by right-clicking
Closes #1276
=> fix: remove click handler for right click

py/h2o_wave/cli.py, py/setup.py
* Kill waved server process created during `wave run` if the app exits with failure.
* Had to update uvicorn to `0.16` due to https://github.com/encode/uvicorn/pull/1278 - uvicorn previously returned 0 exit code no matter what meaning there was no way of distinguishing when the app failed.
* Minor: Remove unnecessary `certifi` dep.
=> fix: Kill hanging waved process when app fails to start.

ui/src/date_picker.tsx, ui/src/plot.tsx
@aalencar FYI #1123 broke the datepicker in Safari. The reason was incorrect datetime format. Fixed it in this PR.
Closes #1300
=> fix: Unify plot time scales.

ui/src/form.tsx, ui/src/tooltip.tsx
@mturoci 
Looks like the `width` prop on Dropdown was not being used. 
`Fluent.Dropdown` has a property called `dropdownWidth` which is used to control the size of the dropdown. I used `width` prop to control the size of the input instead. 
Example using `ui.dropdown` with tooltip and width = 200px:
With tooltip and not specifying the width:
@psinger is this the intended behavior?
Closes #1164
=> fix: set the dropdown input to "width" prop

ui/src/table.test.tsx, ui/src/table.tsx
Fixes missing table rows in specific cases when sorting grouped list. Sorting of grouped list does not sort groups, but only the rows inside the groups.
Closes #1287
=> fix: Allow sorting of grouped by rows

py/examples/button.py, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/vscode-extension/component-snippets.json, ui/src/button.test.tsx, ui/src/button.tsx, website/widgets/form/button.md
Adds optional `path` prop to ui.button component:
```ts
export interface Button {
/** An identifying name for this component. If the name is prefixed with a '#', the button sets the location hash to the name when clicked. */
name: Id
/** The text displayed on the button. */
label?: S
/** The caption displayed below the label. */
caption?: S
/** A value for this button. If a value is set, it is used for the button's submitted instead of a boolean True. */
value?: S
/** True if the button should be rendered as the primary button in the set. */
primary?: B
/** True if the button should be disabled. */
disabled?: B
/** True if the button should be rendered as link text and not a standard button. */
link?: B
/** An optional icon to display next to the button label (not applicable for links). …
```
=> feat: Allow specifying path for button

py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/vscode-extension/component-snippets.json, ui/src/text_annotator.test.tsx, ui/src/text_annotator.tsx, website/widgets/form/text_annotator.md
This PR introduces `readonly` prop for TextAnnotator component. It provides an option to prevent all user interaction with the annotator component.
Updated API looks as follows:
```ts
export interface TextAnnotator {
/** An identifying name for this component. */
name: Id
/** The text annotator's title. */
title: S
/** List of tags the user can annotate with. */
tags: TextAnnotatorTag[]
/** Pretagged parts of text content. */
items: TextAnnotatorItem[]
/** True if the form should be submitted when the annotator value changes. */
trigger?: B
/** True to prevent user interaction with the annotator component. */
readonly?: B
}
```
Closes #1247
=> feat: Allow ui.text_annotator to be read-only

ui/src/plot.tsx
All plot data are shown in tooltip now, not only data user is plotting.
Closes #644
=> feat: Display additional information on plot tooltips

ui/src/stats.tsx
Taking into account #795, stats will not overflow horizontally since the label is going to wrap when it's too long.
After removing `overflow-x: auto`:
@mturoci let me know if I'm missing something on this one since you added `overflow-x: auto`.
closes #1376
=> fix: remove scrollbar from stats

ui/src/textbox.tsx
Fixes [textbox overflow issue](https://github.com/h2oai/wave/issues/1385) when height is set for multiline **ui.textbox**.
Closes #1385
=> Fix: Textbox's scrollbar and text overflow when height is set

py/examples/image_annotator.py, py/examples/tour.conf, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/vscode-extension/component-snippets.json, ui/src/form.tsx, ui/src/image_annotator.tsx, ui/src/text_annotator.tsx, website/sidebars.js, website/widgets/form/image_annotator.md
https://user-images.githubusercontent.com/64769322/166687217-85c0c67c-e6d9-4e30-b1a8-51172e5e70ed.mov
```ts
/** Rectangle (box) annotation. */
interface ImageAnnotatorRect {
/** Start X dimension. */
x1: U
/** End X dimension. */
x2: U
/** Start Y dimension. */
y1: U
/** End Y dimension. */
y2: U
}
/** Defines a particular shape to be used for the annotation. */
interface ImageAnnotatorShape {
rect: ImageAnnotatorRect
}
/** Image annotator tag. */
interface ImageAnnotatorTag {
/** An identifying name for this tag. */
name: Id
/** Text to be displayed. */
label: S
/** HEX or RGB color string used as background for highlighted phrases. */
color: S
}
/** Create an annotator item with initial selected tags or no tag for plaintext. */
interface ImageAnnotatorItem {
/** The annotation shape. */ …
```
=> feat: Image annotator

ui/src/text_annotator.tsx
Fixes unintentional highlighting of non-alphabetical characters preceding the word when annotating the word.
https://user-images.githubusercontent.com/23740173/169311346-18a6f529-e7cf-4b10-8bb4-b2f187865370.mov
Closes #1432
=> Fix annotator selection misses characters issue

auth.go, cmd/wave/main.go, conf.go, website/docs/configuration.md
use the value of oidc-post-logout-redirect-url if set, otherwise follow the previous behavior.
fix/feature: see https://github.com/h2oai/wave/issues/1448 for detailed information
add oidc-post-logout-redirect-url (server param) and H2O_WAVE_OIDC_POST_LOGOUT_REDIRECT_URL (env var) server config options for the highest flexibility
tested with Keycloak 10.0.2
original discussion: https://github.com/h2oai/wave/discussions/1439
Closes #1448
=> feat: add oidc-post-logout-redirect-url config options

ui/src/plot.tsx
When tooltip item value is an array of values these are separated by hyphens now.
Closes #1473
=> Fix: Ranged values in plot tooltip are not shown properly

ui/src/page.tsx
Allows to completely hide card. Useful for apps where it is necessary to hide/unhide cards.
=> Feat: Do not apply card margin when card height/width is 0px

py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, ui/src/file_upload.test.tsx, ui/src/file_upload.tsx
Added option to cancel upload for **ui.file_upload** component for both large and compact mode.
- Large:
https://user-images.githubusercontent.com/23740173/167631558-8bd2c9fb-9bc7-4f7d-ab61-042e5beea32a.mov
- Compact:
https://user-images.githubusercontent.com/23740173/167634203-140042c1-3988-4639-82dd-5fd1846c0036.mov
Closes #1205
=> Allow file upload cancel

ui/src/textbox.tsx
=> fix: Add icon to masked textfield component #1536

app.go, auth.go, py/examples/wizard.py, py/h2o_wave/server.py, server.go, website/docs/security.md
Adds `force_token_refresh` callable to `q.auth`. Upon calling, the `q.auth.access_token` is updated, and waved session is synced.
Since this is server-to-server communication, no cookies are stored (in comparison to server-to-browser) so I had to keep the session ID in the app to make sure I could identify and sync the correct session during refresh. Open to better ideas/suggestions.
Open question: Shall we purge the session in case of an unsuccessful refresh attempt?
Closes #1230
=> feat: Add explicit refresh token callable. #1230

py/examples/combobox.py, ui/src/combobox.test.tsx, ui/src/combobox.tsx
=> fix: Let wave app programmatically change value and choices for combobox

py/examples/plot_theme.py, tools/showcase/Makefile, ui/src/plot.tsx
This PR replaces the SVG renderer with the default canvas renderer. The main reason for picking the SVG renderer was the ease of theming via CSS variables unavailable in the canvas. Surprisingly, it seems like G2 is able to update theming plots faster than the browser to repaint the UI on CSS variables change (most probably due to too complex DOM structure, but didn't dive deeper).
Closes #1562
Closes #1581 - Safari render
=> fix: Use canvas renderer to avoid subtle G2 bugs. #1562

ui/src/plot.tsx
Filters out annotation marks before setting geometry interactivity to prevent regression.
Closes #1586
=> Fix: Prevent regression caused by non-interactive plots

py/h2o_wave/core.py, py/tests/test_python_server.py
Prevents a memory leak.
HTTPX (our HTTP client) lib accepts `BufferedReader` for multipart (file) uploads, but somehow doesn't close file handles when finished so it's necessary to do it ourselves - this PR.
=> fix: Prevent memory leak caused by unclosed file handles during site.upload.

ui/src/plot.tsx
=> Fix: Missing tooltips for histogram with time x_scale

ui/src/file_upload.tsx
=> Fix: Success message without file names when ui.file_upload inside ui.dialog

ui/src/textbox.test.tsx, ui/src/textbox.tsx
* allow Textbox "value" to be set from wave app
* add tests for TextField and MaskedTextField
* fix warning about act() in tests
https://user-images.githubusercontent.com/15820796/186417390-982c280e-4dff-44cb-a056-2d86d76bace6.mov
closes #1578
=> fix: Allow setting Textbox "value" dynamically

ui/src/theme.ts
Added `isInverted` prop to `loadTheme` to show correct colors for dark themes.
- **Before**
- **After**
Closes #1608
=> fix: Use correct semantic colors for dark themes

ui/src/text_annotator.tsx
The new character level annotations feature implementation has caused the inability of multiline selections. To be more precise - the text was automatically annotated when mouse went outside of text while annotating (even in the case while dragging the mouse between the lines because of the margin in between them).
This fix ensures that no annotation is made when mouse leaves the text, instead the annotation is made after `onMouseUp` event.
https://user-images.githubusercontent.com/23740173/190928824-977ca065-b9bd-4db5-bbee-1230aad2707d.mov
=> fix: Multiline selection support for ui.text_annotator

ui/src/combobox.test.tsx
Add test to ensure a new typed value is a string instead of an array like in Wave 0.22.
closes #1615
=> test: Add test for single-valued Combobox

py/examples/text_annotator.py, ui/src/text_annotator.test.tsx, ui/src/text_annotator.tsx, website/widgets/form/text_annotator.md
Javascript's newline escape sequences `\n` and `\r` are now transformed into line breaks in **ui.text_annotator**:
```py
ui.text_annotator_item(text=' is a member of the hip\rhop super\ngroup ')
```
These escape characters are only included in selection when user spans the selection through multiple lines.
Closes #1358
=> Feat: Make ui.text_annotator to respect \n and \r in text

ui/src/wide_gauge_stat.tsx, ui/src/wide_series_stat.tsx
This PR makes the behavior consistent with `ui.wide_gauge_stat` (#1566) and prevents disturbing and unnecessary moving of  numeric/textual value when it changes.
https://user-images.githubusercontent.com/23740173/191020785-bca76f88-d989-4eed-b13b-673bd614c3e1.mov
Closes #1592
=> Fix: Prevent ui.wide_series_stat moving when textual values change

py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/vscode-extension/component-snippets.json, ui/src/file_upload.tsx, ui/src/index.scss, ui/src/theme.ts
Adds `required` prop to `ui.file_upload` component. Updated API:
```ts
export interface FileUpload {
/** An identifying name for this component. */
name: Id
/** Text to be displayed in the bottom button or as a component title when the component is displayed compactly. Defaults to "Upload". */
label?: S
/** True if the component should allow multiple files to be uploaded. */
multiple?: B
/** List of allowed file extensions, e.g. `pdf`, `docx`, etc. */
file_extensions?: S[]
/** Maximum allowed size (Mb) per file. No limit by default. */
max_file_size?: F
/** Maximum allowed size (Mb) for all files combined. No limit by default. */
max_size?: F
/** The height of the file upload, e.g. '400px', '50%', etc. Defaults to 300px. */
height?: S
/** The width of the file upload, e.g. '100px'. …
```
=> feat: Add required prop to ui.file_upload

ui/src/dropdown.test.tsx, ui/src/dropdown.tsx
On line 189, since `filteredItems` is intialized with `items`, `setFilteredItems` was mutating `items` when it set `i.checked = checked` which is definitely an antipattern, plus `items` uses `useMemo` which should only change when its dependencies change.
`189: selectAll = (checked = true) => () => setFilteredItems(filteredItems.map(i => { i.checked = checked; return i })),`
`filteredItems` should represent the displayed items and should rely on `items` as single source of truth. The refactoring makes it so that we change `items` and the changes are reflected to `filteredItem` through `useEffect`. Same for searching.
I believe this is a better mental model.
I fixed a bug where multi-valued dialog Dropdown was setting wave args to string when it only had a single value selected and it was …
=> fix: Add support to dynamically change Dropdown value

ui/src/table.tsx
=> fix: Reduce space between searchbar and table

ui/src/plot.tsx
Closes #617
@lo5 can you please have a quick look? Seems like the break statements I removed were there on purpose, but I couldn't figure out what it could be. I ran the changes through our visual regression testing and it doesn't break any of our plot examples so should be safe.
=> fix: Allow formatting for more than just 1st ui.mark. #617

py/examples/menu.py, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/vscode-extension/component-snippets.json, ui/src/menu.tsx, website/widgets/form/menu.md
https://github.com/h2oai/wave/issues/1577
Added a 'label' parameter to the UI component of wave. This label will be displayed beside the arrow for the menu dropdown. It will also be clickable, i.e. the dropdown will open on clicking the arrow as well as the label.
=> feat: Added label parameter to ui.menu

.vscode/launch.json, py/examples/image_annotator.py, py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/vscode-extension/component-snippets.json, ui/src/image_annotator.test.tsx, ui/src/image_annotator.tsx, ui/src/image_annotator_polygon.ts, ui/src/image_annotator_rect.ts, ui/src/setupTests.ts, ui/src/theme.ts, website/widgets/form/image_annotator.md
https://user-images.githubusercontent.com/64769322/192780336-c3d5fc43-8186-4d66-894f-c0fac4e6bb1e.mov
@lo5
```ts
/** Create a polygon annotation point with x and y coordinates.. */
export interface ImageAnnotatorPoint {
/** `x` coordinate of the point. */
x: F
/** `y` coordinate of the point. */
y: F
}
/** Create a polygon annotation shape. */
export interface ImageAnnotatorPolygon {
/** List of points of the polygon. */
items: ImageAnnotatorPoint[]
}
```
```py
ui.image_annotator_item(tag='p', shape=ui.image_annotator_polygon([
ui.image_annotator_point(x=828.2142857142857, y=135),
ui.image_annotator_point(x=731.7857142857142, y=212.14285714285714),
ui.image_annotator_point(x=890.3571428571429, y=354.6428571428571),
ui.image_annotator_point(x=950.3571428571429, y=247.5)
])),
```
return …
=> feat: Polygon support for image annotator

auth.go
Ref: https://discord.com/channels/1022255416454946906/1039540632609378374/1039540632609378374
```
2022/11/08 13:42:12 # {"client":"<redacted>","err":"oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"Token is not active\"}","t":"refresh_oauth2_token"}
2022/11/08 13:42:12 # {"error":"invalid session","session_id":"70a2ef33-8eca-430c-a7ec-382783418f09","t":"oauth2_session"}
2022/11/08 13:42:12 # {"client":"<redacted>","err":"oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"Token is not active\"}","t":"refresh_oauth2_token"}
2022/11/08 13:42:12 http: panic serving <redacted>: runtime error: invalid memory address or nil pointer dereference
goroutine 6004 [running]: …
```
=> fix: Don't access id_token if oauth2 workflow previously failed

ui/src/app.tsx, ui/src/button.tsx
This PR provides an override of icon colour for all disabled FluentUI buttons.
https://user-images.githubusercontent.com/23740173/203029158-a6c771f6-5731-4253-9a94-8a953f300aad.mov
Closes #1664
=> fix: Make disabled ui.button icon and text colours consistent #1664

website/docs/architecture.md, website/docs/getting-started.md
The syntax used for footnotes was incorrect, making them render incorrectly (they were rendering as footnote references instead).
Fixes #1720
=> docs: Fix the footnote links not working

py/examples/meta_stylesheet.py, website/docs/custom-css.md
Adds the example of how to apply the css stylesheet stored on the Wave server.
=> docs: Show how to use local CSS file as stylesheet.

cmd/wave/main.go
Closes #1711.
Our code checks whether any of the OIDC required params are not empty in the function _checkEmptyOIDCValues()_. This function counts the amount of empty OIDC params. It returns a slice containing the empty OIDC params detected as well as a boolean which is true when some but not all OIDC params are empty.
After calling the function we just check if this boolean is true to display the required warning. 
Collaborators: 
@Qingyang-Sophia
@aruiz2
=> Show a warning when at least one OIDC param detected, but not all are set

website/src/css/custom.css
This PR fixes the home page hero button text color in dark mode.
Closes #1740
=> docs: fix the home page button in dark mode #1740

py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/vscode-extension/component-snippets.json, ui/src/frame.tsx, website/widgets/content/frame.md
Added a parameter called `compact` in the `State` interface of `frame.tsx`. Users can specify whether they want the frame cards to have title and paddings or not. `compact` defaults to `False`.
Example:
Frame card with no padding specified:
The changes are reflected above. The first frame card with default padding (`compact` not specified), the second frame card with padding specified, and the third frame card with no padding specified. 
The code used for testing the changes above:
```py
page['example1'] = ui.frame_card(
box='1 1 -1 4',
title='Frame card with default padding',
path='https://example.com',
)
page['example2'] = ui.frame_card(
box='1 5 -1 4',
title='Frame card with padding specified',
path='https://example.com',
compact=False
)
page['example3'] = ui.frame_card(
box='1 9 -1 …
```
=> feat: Allow users to remove paddings on frame cards

.vscode/launch.json, file_server.go, py/h2o_wave/core.py, py/tests/test_python_server.py, py/tests/test_python_server_async.py
* Raise an err if there is any - same behavior like the rest of alike functions.
* Create a file for the stream to write into only in case of 200 status code.
Needs discussion: https://github.com/h2oai/wave/issues/1627#issuecomment-1254702592
Closes #1627
=> feat: Add proper err handling to site.download function and allow extensionless file downloads. #1627

auth.go
=> feat: Log the upstream error if oauth token exchange fails. #1761

.github/workflows/publish-docs.yml, .github/workflows/release-wave-nightly.yml, .github/workflows/release-wave.yml, website/docs/contributing.md
Needs discussion: Shall we use the same go version for WaveDB as well? cc @lo5
Update needed due to: https://github.com/golang/go/issues/32350
=> fix: Do not serve JS files with plaintext MIME type on Windows by upgrading go to 1.19.

website/docs/deployment.md
I was just running through the docs and was unable to get the Wave app to connect to the `waved` server when I ran the `uvicorn` command specified in the documentation.
I reached out via the **Discussions** threads and quickly received some help from @mturoci.
The documentation didn't mention the need to set the H2O_WAVE_APP_ADDRESS environment variable (at least not directly on the deployment page).
closes #1807
=> ENV setup required when deploying with Uvicorn

py/h2o_wave/types.py, py/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/showcase/showcase.py, tools/vscode-extension/component-snippets.json, ui/src/form.tsx, website/widgets/form/inline.md
This change adds the `height` prop for ui.inline component.
```ts
interface Inline {
/** The components laid out inline. */
items: Component[]
/** Specifies how to lay out the individual components. Defaults to 'start'. */
justify?: 'start' | 'end' | 'center' | 'between' | 'around'
/** Specifies how the individual components are aligned on the vertical axis. Defaults to 'center'. */
align?: 'start' | 'end' | 'center' | 'baseline'
/** Whether to display the components inset from the parent form, with a contrasting background. */
inset?: B
/** Custom height  in `px`, `vh` or `rem`. Use '1' to fill the height of the remaining space. E.g. '100vh', '300px' or '1'. */
height?: S
}
```
As API description says, the accepted values are the following CSS units: `px`, `vh` or `rem`. It is also …
=> feat: Allow specifying height for ui.inline #1780

.vscode/launch.json, ui/src/dropdown.test.tsx, ui/src/dropdown.tsx
This PR resolves half of the #1815 by proper mutations on `model.value`.
Current `handle_on` runs at most one handler function (depending on match). This is problematic since since we always return the current `#` in q.args (https://github.com/h2oai/wave/commit/bc409b3a6d3e0a403e637af60084e36c75561df2#diff-093127603bee40a36f6c601028f9af200504cb9dba3a73b808ae2b2643e5980c). This results in `handle_on` always handling the hash part if it matches. ignoring any other potential form outputs, e.g. dropdown value.
Fixing the `handle_on` would be a massive breaking change though so I suggest deprecating it in favor of newer mechanism proposed by @Far0n. cc @lo5 
The workaround for #1815 once this PR is merged would be to either completely ditch `handle_on` and fallback to if else statements or use …
=> fix: Properly mutate page state during dropdown events.

py/h2o_wave/cli.py
This PR allows for deploying Wave server and Wave apps on separate machines.
The problem was that hardcoded `localhost` would instruct uvicorn to only handle local requests. Using a proper host from env variable resolves this.
=> fix: Use proper host when starting up the Wave app.

py/examples/table_pagination.py, py/h2o_lightwave/h2o_lightwave/types.py, py/h2o_lightwave/h2o_lightwave/ui.py, py/h2o_wave/h2o_wave/types.py, py/h2o_wave/h2o_wave/ui.py, r/R/ui.R, ui/src/table.test.tsx, ui/src/table.tsx
Fixes the regression caused by #1724 when paginated table became frozen after the page change.
Also fixes API description typo for `single` prop and updates the API description for `groupable` to align with the [current implementation](https://github.com/h2oai/wave/commit/294e642b0a0d8071091dc4b4914a05a89b0ed50b).
=> fix: Prevent table reset on items change for paginated table

ui/src/time_picker.tsx
Fixes the regression of time picker where user was unable to properly open the time picker in case multiple time pickers are present on the page, e.g. in `time_picker.py` example.
=> fix: Unable to open time picker

card.go, go.mod, go.sum, py/examples/counter_broadcast.py, py/examples/counter_multicast.py, py/examples/counter_unicast.py, ts/index.ts
Allows for:
```py
from h2o_wave import Q, ui, main, app
@app('/')
async def serve(q: Q):
q.page['wizard'] = ui.form_card(box='1 1 2 4', items=[
ui.text_xl(name='text_name', content='Wizard'),
ui.textbox(name='textbox_name', label='Textbox'),
ui.inline(items=[
ui.button(name='back', label='Back'),
]),
])
q.page['wizard'].text_name.content = 'foo'
q.page['wizard'].textbox_name.label = 'foo'
q.page['wizard'].back.label = 'foo'
q.page['header'] = ui.header_card(box='4 6 4 1', title='Header', subtitle='Subtitle', secondary_items=[
ui.button(name='button_name', label='Button'),
])
q.page['header'].button_name.label = 'foo'
q.page['example'] = ui.form_card(box='5 1 4 5', items=[
ui.buttons([
ui.button(name='primary_button', label='Primary', primary=True),
]),
]) …
```
=> feat: Allow by-name component access. #148

py/examples/copyable_text.py, py/h2o_lightwave/h2o_lightwave/types.py, py/h2o_lightwave/h2o_lightwave/ui.py, py/h2o_wave/h2o_wave/types.py, py/h2o_wave/h2o_wave/ui.py, r/R/ui.R, ui/src/copyable_text.tsx, website/widgets/form/copyable_text.md
Updated API description:
```ts
export interface CopyableText {
/** Text to be displayed inside the component. */
value: S
/** The text displayed above the textbox. */
label: S
/** An identifying name for this component. */
name?: S
/** True if the component should allow multi-line text entry. */
multiline?: B
/** Custom height in px (e.g. '200px') or use '1' to fill the remaining card space. Requires `multiline` to be set. */
height?: S
}
```
Closes #1823
=> feat: Allow specifying '1' for height in copyable text to fill the remaining space

ui/src/copyable_text.test.tsx, ui/src/copyable_text.tsx
This PR positions the copy button relative to label container instead of the textfield component. By this change the button is not overlapping the text in case of multiline labels.
Closes #1883
=> fix: Prevent copy button from overlapping multiline labels in ui.copyable_text

ui/src/time_picker.test.tsx, ui/src/time_picker.tsx
Updating of wave args if now moved from time picker's `onAccept` to `onChange` to make sure it is updated every time user changes the time, not only on popup close.
Closes #1889
=> fix: Update wave args of ui.time_picker on every time change #1889

py/demo/common.py, py/demo/dashboard_blue.py, py/demo/dashboard_cyan.py, py/demo/dashboard_grey.py, py/demo/dashboard_mint.py, py/demo/dashboard_orange.py, py/demo/dashboard_purple.py, py/demo/dashboard_red.py
Closes #1867 
Updated dashboard demo app to:
- include h2o logo
- directly render links in the header using tabs
Links are now accessible without needing to click the hamburger menu.
=> feat: Render dashboard demo app links in header and add h2o logo

py/h2o_lightwave/h2o_lightwave/types.py, py/h2o_lightwave/h2o_lightwave/ui.py, py/h2o_wave/h2o_wave/types.py, py/h2o_wave/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/vscode-extension/component-snippets.json, ui/src/markup.tsx, website/widgets/content/markup.md
Closes #1922
Added a `compact` attribute to the `State` interface of `markup.tsx`. Users can now specify whether they want the markup card to include the paddings or not. `compact` attribute defaults to `False`.
Differences between `compact` invocations are depicted above.
The code used to produce the markup cards above is included below.
```py
menu = '''
<p>
<span>Spam</span>
<span>Ham</span>
<span>Eggs</span>
</p>
'''
page['example1'] = ui.markup_card(
box='4 1 3 2',
title='Markup card with default padding (compact attribute not invoked)',
content=menu,
)
page['example2'] = ui.markup_card(
box='4 3 3 2',
title='Markup card with padding (compact=False)',
content=menu,
compact=False
)
page['example3'] = ui.markup_card(
box='4 5 3 2',
title='Markup card with no padding (compact=True)', …
```
=> feat: Implement `compact` attribute for markup card

py/examples/button.py, py/h2o_lightwave/h2o_lightwave/types.py, py/h2o_lightwave/h2o_lightwave/ui.py, py/h2o_wave/h2o_wave/types.py, py/h2o_wave/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/vscode-extension/component-snippets.json, ui/src/button.test.tsx, ui/src/button.tsx, website/widgets/form/button.md
This change brings the `commands` attribute for _ui.button_ where you can provide other relevant actions for the button that are displayed in the context menu.
```ts
export interface Button {
/** An identifying name for this component. If the name is prefixed with a '#', the button sets the location hash to the name when clicked. */
name: Id
/** The text displayed on the button. */
label?: S
/** The caption displayed below the label. */
caption?: S
/** A value for this button. If a value is set, it is used for the button's submitted instead of a boolean True. */
value?: S
/** True if the button should be rendered as the primary button in the set. */
primary?: B
/** True if the button should be disabled. */
disabled?: B
/** True if the button should be rendered as link text and not a …
```
=> feat: Dropdown button #1887

ui/src/table.test.tsx, ui/src/table.tsx, ui/src/tag_table_cell_type.tsx
After fix:
Before fix:
Closes #1905
=> fix: Filter out empty strings for tags and filter options #1905

py/apps/tour/app.toml, py/examples/link.py, py/examples/meta_icon.py, py/examples/meta_title.py, py/examples/site_async.py
A relative URL with `/` in the beginning replaces the entire path name of the base URL.
What we want here is to appended a relative URL to the full base URL and this can be achieved by removing the leading slash.
https://user-images.githubusercontent.com/23740173/234636257-ad5ee447-fff2-46b2-a066-3e60bfe1f4b1.mov
Closes #1875
=> feat: Make tour examples to support path-based routing #1875

client.go
Fix to make order of q.args the same as in 0.24 (although still not guaranteed).
=> fix: Make sure the args order is the same as in 0.24.

ui/src/plot.tsx
This PR fixes a bug introduced by [this commit ](https://github.com/h2oai/wave/commit/13e6c5d5186fc178cf65a2d16b3ed40d5b87b683#diff-23f130cc86661f6f1f9e450c94cb4b477dc6c8c0ec848de8eb9c1bf3a5ca3b88) where plot listens only for `meta.theme` changes but not for `meta.themes` when updating colors.
https://github.com/h2oai/wave/assets/23740173/fa4a85cf-aa13-4dea-86ed-1bdcdb721299
Closes #1971
=> fix: Update plot color in theme_generator.py #1971

py/examples/chatbot_events_stop.py, website/widgets/ai/chatbot.md
This PR fixes the issue where text input content was appended into messages after clicking on the _Stop generating_ button in the `chatbot_events_stop.py` tour example.
https://github.com/h2oai/wave/assets/23740173/c163f25a-bae4-4bf0-9f0d-48d762b7b7a5
=> fix: Do not append text input into messages when stopping the generation

py/h2o_lightwave/h2o_lightwave/routing.py, py/h2o_wave/h2o_wave/routing.py
Pdoc builds the docs correctly when curly braces `{}` are used.
The problem is with [docusaurus using the MDX compiler](https://github.com/facebook/docusaurus/issues/3018) for `.md` files generated by pdoc while building the website.
In MDX, curly braces are reserved for expressions so in our case the MDX compiler is looking for a `fruit` variable which is, obviously, not defined - `@on('#foo/{fruit}')`. We can fix this by writing an expression inside the curly braces which returns what we want, in our case `{"{fruit}"}`.
Closes #1880
=> fix: Show curly braces in pydocs correctly #1880

py/h2o_wave/h2o_wave/cli.py, py/h2o_wave/h2o_wave/share.py
Python client for reverse proxy tunnel, integrated into Wave CLI.
Detailed documentation to be done in #1954 once this PR is merged and proxy tunnel server deployed in prod.
=> feat: Wave share client.

ui/src/image_annotator.test.tsx
This PR fixes the failing ui.image_annotator test.
=> fix: Set active tool other than 'select' to emit the click event

py/docs/templates/config.mako, py/docs/templates/text.mako
___
https://github.com/h2oai/wave/assets/23740173/ac9d3bc3-fbf9-4278-a72f-a63830e1ec0f
Closes #2078
Closes #1667
=> feat: Use absolute URLs in API docs #2078

.vscode/launch.json, card.go, py/h2o_lightwave/h2o_lightwave/core.py, py/h2o_wave/h2o_wave/core.py, py/tests/test_python_server.py, py/tests/utils.py, tools/showcase/showcase.py, ts/index.ts, ui/src/plot.tsx, website/widgets/form/visualization.md
This PR introduces support for non-packed data buffers within `ui.visualization` components - form cards.
By-name access is supported as well, buffers behave in the same way for form components as they do in cards.
```py
import time
from h2o_wave import site, ui, data
page = site['/demo']
page.add('example', ui.form_card(
box='1 1 -1 8',
items=[
ui.visualization(
name='my_plot',
plot=ui.plot([ui.mark(type='interval', x='=profession', y='=salary', y_min=0)]),
data=data(fields='profession salary', rows=[
('medicine', 23000),
('fire fighting', 18000),
('pedagogy', 24000),
('psychology', 22500),
('computer science', 36000),
]),
),
ui.visualization(
plot=ui.plot([ui.mark(type='interval', x='=profession', y='=salary', y_min=0)]),
data=data(fields='profession salary', rows=[
('medicine', 21000), …
```
=> feat: Add data buffer support to components (form card). #441

ui/src/spinbox.test.tsx, ui/src/spinbox.tsx
=> fix: Allow dynamic value change for spinbox #1154

ui/src/range_slider.test.tsx, ui/src/range_slider.tsx
=> fix: Allow dynamic value change for range slider #1154

ui/src/choice_group.test.tsx, ui/src/choice_group.tsx
=> fix: Allow dynamic value change for choice group #1154

ui/src/picker.test.tsx, ui/src/picker.tsx
=> fix: Allow dynamic value change for picker #1154

ui/src/dropdown.test.tsx, ui/src/dropdown.tsx
___
Currently the value/values prop can be updated dynamically through Wave app for base dropdown and for both single and multi-valued dialog dropdown. However the dynamic update of choices can be done only for the base dropdown. This PR unifies the behavior and brings support for dynamic update of choices also for multi-valued and single-valued dialog dropdown.
=> fix: Dynamic choices change for single/multi-valued dialog dropdown #1154

ui/src/checklist.test.tsx, ui/src/checklist.tsx, ui/src/combobox.test.tsx, ui/src/combobox.tsx, ui/src/dropdown.test.tsx, ui/src/dropdown.tsx, ui/src/header.tsx, ui/src/nav.test.tsx, ui/src/nav.tsx, ui/src/tab.test.tsx, ui/src/tab.tsx, ui/src/tabs.test.tsx, ui/src/tabs.tsx
**The PR fulfills these requirements:** (check all that apply)
___
This PR addresses all issues found after final revision of #1154. Included issues are:
- **Checklist** - set values to `None`, select value manually, set values to `None` once again (unable to set to `None`)
- **Tabs** - dynamic value change is fully supported for `ui.tab_card` only, but not for `ui.tabs` - try to set value dynamically, select tab manually, set value dynamically to the same value as before (Tab is not switching)
- **Combobox single/multi** - when `choices` are set to `None` it leads to endless loop
- **Dropdown - dialog single/multi** - when `choices` are set to `None` it leads to endless loop
- **Nav** - user was unable to dynamically unselect all items by specifying `value=None` within the Wave app when …
=> fix: Make dynamic value change consistent

client.go, protocol.go, ts/index.ts, ui/src/ui.ts
The root cause of the problem described in the corresponding issue was:
* Client1 renders a form with value.
* UI changes are propagated to the rest of connected clients, (client2).
* UI state is set as dirty in the browser side, due to explicit textbox value. State is same across all clients.
* Client1 clicks the button, q.args with the correct state (btn + textbox) is submitted and cleared.
* UI changes are propagated to all the clients again, but now client1 has fresh UI state, while client2 has the old one still as there was no user interaction that would submit and clear the local args (local state).
This PR sends a clear event to all the connected clients whenever user interaction happens on any of them.
Closes #1705
=> fix: Clear dirty UI state across clients on broadcast/multicast user interaction for consistency. #1705

e2e/test_copy_button.py, ui/src/copyable_text.tsx, ui/src/markdown.tsx
___
This PR adds e2e tests for #2025.
Unit tests for testing the button visibility on hover over **copyable_text/markdown code block** were not enough due to [limitations](https://github.com/testing-library/jest-dom/issues/59) of `nwsapi` lib used by JSDOM.
=> chore: Add e2e tests for showing clipboard copy button #2025

py/docs/templates/text.mako
___
https://github.com/h2oai/wave/assets/23740173/5df349d5-dde6-4306-aa38-6169759f2063
Closes #2112
=> fix: Trim trailing dash in api docs #2112

ui/src/vega.tsx
=> feat: removed reserved space for empty titles in vega_card #1923

py/examples/plot_events_disabled.py, ui/src/plot.tsx
@marek-mihok - can you make a code review and a thorough QA to check if everything works as expected?
* The returned event data is now the same as passed in. Prior to this PR, the data could have been mutated eg when `scale='time'` to timestamps.
* Slight return format change: The events are returned in a flat array instead of a nested (`[[]]`) array for line, area plots etc.
=> fix!: Return originally passed data as select events instead of mutated ones.

py/examples/background_progress.py, py/examples/form_visibility.py, ui/src/form.tsx, ui/src/header.tsx, website/widgets/form/inline.md
@marek-mihok - can you make a code review and a thorough QA to check if everything works as expected?
This is a rewrite of #1988 for #1974.
The reason some components shrunk drastically was wrong use of default `align='center` for case when `direction='column'`. This PR sets the following defaults:
* All components should try to occupy all the available space unless explicitly specified otherwise. This rule is in sync with regular `form_card.items`.
* The above default does not apply for cases when explicit alignment for main axis (`justify`) is chosen. In such case, the default width should correspond to the component's content, be it a label or anything else.
=> chore: Use maximum available space in ui.inline instead of hardcoded constant. #1974

ui/src/card_menu.tsx, ui/src/parts/styleConstants.ts, ui/src/plot.tsx, ui/src/vega.tsx
___
After improvement:
Before:
Diff:
With all themes:
https://github.com/h2oai/wave/assets/23740173/53e79077-470e-4784-b9f1-ff64f839a974
Closes #2127
=> feat: Improve visibility of card commands button #2127

socket.go
This PR solves the problem when websockets is not able to reconnect due to expired session. Instead of noop, it now redirects users to a login screen to renew the session.
As per [WS spec](https://www.rfc-editor.org/rfc/rfc6455):
> If the status code received from the server is not 101, the client handles the response per HTTP [[RFC2616](https://www.rfc-editor.org/rfc/rfc2616)] procedures.  In particular, the client might perform authentication if it receives a 401 status code; the server might redirect the client using a 3xx status code (but clients are not required to follow them), etc.  Otherwise, proceed as follows.
Clients (browser in our case) are not required to follow HTTP redirects, so they do not. For that reason, redirect request is sent as payload which is then handled …
=> feat: Redirect to login on WS reconnect if auth specified

website/docs/security.md
Update to security docs regarding setup of OpenID with Azure
=> azure openid faq update

ui/src/nav.test.tsx, ui/src/nav.tsx, website/widgets/content/navigation.md
___
https://github.com/h2oai/wave/assets/23740173/fefd6995-3ee6-4a21-957d-bc271fd74684
Closes #1932
=> feat: Allow nav_item to be opened in a new tab/window #1932

py/h2o_wave/hatch_build.py
URL generated for fetching should be  of the format: `wave-{version}-{operating_system}-{arch}`
But the fetch url being generated was using `platform` instead of the `operating_system`.
Since this variable is set on the build time. Changed the `hatch_build.py` file. This will also change the `metadata.py` file that gets generated.
Closes h2oai#2177
=> fix: Use proper path for wave fetch. #2177

ui/src/picker.test.tsx, ui/src/picker.tsx
___ 
The problem was the implementation of `onEmptyResolveSuggestions` callback. As Fluent API description says, it is
> A callback for what should happen when suggestions are shown without input provided. Returns the already selected items so the resolver can filter them out.
In our case it was returning initial tags (`() => tags`) instead of filtered ones.
https://github.com/h2oai/wave/assets/23740173/6c7ab461-ca83-418a-bed7-3c3d166d6b89
Closes #1985
=> fix: Do not show selected tags in picker suggestions when no input is provided #1985

py/examples/table_events_select.py, ui/package-lock.json, ui/package.json, ui/src/table.test.tsx, ui/src/table.tsx
___
Fixed by updating FluentUI to slightly [newer version](https://github.com/microsoft/fluentui/commit/fb377e0b4400b99499d69e9ca956fd433f3e2804) supporting custom `onItemsChanged` event callback fired after Fluent internal `items` are updated but before `onSelectionChanged`. This way we can prevent `select` event from being emitted anytime `items` are updated. Now the only way of firing the event is to select/deselect row or select/deselect all rows.
Both unit and visual regression tests pass after FluentUI update.
https://github.com/h2oai/wave/assets/23740173/8e541660-bcf8-4ca5-b5d1-a62f3468ccc9
Closes #2196
=> fix: Emit table select event only if selection changes  #2196

ui/src/combobox.test.tsx
___
In updated version of FluentUI there is no longer the `span` with a `title` attribute, but `span` with a text content instead.
```html
<span class="ms-ComboBox-optionText css-158">Cyan</span>
```
=> fix: Adapt combobox unit tests to FluentUI internal change

studio/static/studio.css, studio/studio.js, studio/studio.py
___
https://github.com/h2oai/wave/assets/23740173/1a7943b5-9471-4615-b33c-99107036e35f
The core function doing the magic of package installation is our `pip` function which uses `subprocess.Popen`. In contrast to `subprocess.run` waiting for the result, Popen allows us to handle custom logic during its execution. This allows us to read its progress output and show display it to user. For reading the output from within the app, we forward stdout into `subprocess.PIPE`. We also use `text=True` attribute to get output as a string instead of bytes object. 
Popen is used inside context manager to properly close the pipes after the execution and handle other cleanup logic. Inside the Popen context we run the event loop checking …
=> feat: Allow installing custom packages inside Wave Studio #2193

.github/workflows/publish-conda.yml, .github/workflows/release-wave.yml, py/h2o_wave/conda/meta.yaml
____
The problem was that the package only supports the version of python it was built in. It can be solved by specifying `noarch: python` inside `meta.yaml` conda config file. The result is the single platform independent package supporting multiple python versions.
Also update of the pipeline build action (`amauryval/publish_conda_package_action`) to version 2.0.3 is necessary, because it allows specifying `noarch` value as the `Platforms` parameter.
Closes #2227
=> fix: Make conda package support multiple python versions #2227

ui/src/notification_bar.tsx
____
Fix applies notification text color for the close icon.
Closes #2241
=> fix: Make notification close button contrast for any theme #2241

ui/src/spinbox.test.tsx, ui/src/spinbox.tsx
___ 
The problem was with `calculatePrecision` function not working with scientific (exponential) notation numbers.
The fix converts scientific notation numbers to regular decimal numbers and it uses `Number.toFixed()` for conversion. 
This solution is simple but works for numbers with up to 20 decimal points. To support more decimal points, it would need more complicated solution (something like [this one](https://gist.github.com/jiggzson/b5f489af9ad931e3d186?permalink_comment_id=3723670#gistcomment-3723670) but more reliable).
I think 20 decimal points should be enough for now and if it won't, someone will open the new issue. Wdyt @mturoci ?
Closes #1525
=> fix: Support up to 1e-20 numbers in ui.spinbox #1525

py/examples/toolbar.py, py/h2o_lightwave/h2o_lightwave/types.py, py/h2o_lightwave/h2o_lightwave/ui.py, py/h2o_wave/h2o_wave/types.py, py/h2o_wave/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/vscode-extension/component-snippets.json, ui/src/button.test.tsx, ui/src/card_menu.test.tsx, ui/src/card_menu.tsx, ui/src/link.tsx, ui/src/table.test.tsx, ui/src/toolbar.test.tsx, ui/src/toolbar.tsx, website/widgets/content/toolbar.md
___
Adds `path` and `download` attributes to **ui.command** to support the same behavior as `ui.link()`:
```tsx
export interface Command {
/** An identifying name for this component. If the name is prefixed with a '#', the command sets the location hash to the name when executed. */
name: Id
/** The text displayed for this command. */
label?: S
/** The caption for this command (typically a tooltip). */
caption?: S
/** The icon to be displayed for this command. */
icon?: S
/** Sub-commands, if any */
items?: Command[]
/** Data associated with this command, if any. */
value?: S
/** The path or URL to link to. The 'items' and 'value' props are ignored when specified. */
path?: S
/** True if the link should prompt the user to save …
```
=> feat: Make ui.command to support path and download props #2224

py/examples/picker_selection.py, ui/src/picker.test.tsx, ui/src/picker.tsx
Closes #273 
As explained in the issue, the picker `data-test` attribute is missing from the DOM once the `max_choices` defined for the FluentUI TagPicker component is reached. With the change in this PR, a new `data-test` attribute is added to the remove button for the choices selected in the picker. This allows a Cypress test to locate the picker remove button with the `data-test` attribute and click it. Since the `max_choices` is no longer satisfied, the `input` element with the picker `data-test` attribute is added back to the DOM.
This was accomplished by using `removeButtonIconProps` on `TagPicker` to add a new `data_test` attribute that includes the picker name prefixed with `remove_`. The code in `ui/src/picker.tsx` …
=> feat: Add data-test attribute to picker item remove button #273

tools/showcase/showcase.py, ui/src/form.tsx
___
The problem was that left margin for ui.inline horizontally laid components adds to total component width causing the overflow. Since something like `boxSizing: "margin-box"` does not exist, the issue is fixed by replacing left margin with left padding and using `boxSizing: "border-box"` which accounts for both borders and paddings when calculating component dimensions.
This PR also includes a fix for firefox visual regression tests incompatibility with new `H2O_WAVE_RECONNECT_TIMEOUT` (#2252).
Solution tested across all browsers.
Also both unit and visual regression tests pass.
Closes #2251
=> fix: Include spacing in width for inline horizontal components #2251

ui/src/table.test.tsx, ui/src/table.tsx
___
The problem was in reducer inside `onSortChange` function 
```tsx
setFilteredItems(filteredItems => [...groups]
// sorts groups by startIndex to match its order in filteredItems
.sort((group1, group2) => group1.startIndex - group2.startIndex)
.reduce((acc, group) => [...acc, ...filteredItems.slice(group.startIndex, acc.length + group.count).sort(sortingF(column, sortAsc))],
[] as any[]) || [])
``` 
adding `acc.length + group.count` filtered items into the final array even in case of empty group present (`group.count` equal to `0`) but `acc.length` having non-zero value most of the time.
Fixed by conditional adding of items:
```tsx
group.count
? [...acc, ...filteredItems.slice(group.startIndex, acc.length + …
```
=> fix: Sort items correctly when empty custom group is present #2268

py/examples/toolbar.py, ui/src/audio_annotator.test.tsx, ui/src/parts/range_annotator.tsx, ui/src/parts/waveform.tsx, website/widgets/form/link.md
____
This PR fixes several issues based on the v1.0.0 pre-release QA, namely:
- **Audio annotator**: Wrong annotator dimensions if Wave app is loaded when browser tab is not visible
- **Audio annotator**: In [specific scenario](https://github.com/h2oai/wave/issues/2276#issuecomment-1968481977) user was able to activate empty tag and annotate with it
- **Toolbar**: Download prop example was not working due to link being from different origin.
TBD:
Closes #2276
=> feat: v1.1.0 pre-release QA based fixes #2276

client.go
Fixes FF websocket issue. @marek-mihok please verify if works for you as well.
Part of #2276
=> fix: Close websocket connections as per spec.

py/h2o_lightwave/h2o_lightwave/types.py, py/h2o_lightwave/h2o_lightwave/ui.py, py/h2o_wave/h2o_wave/types.py, py/h2o_wave/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/vscode-extension/component-snippets.json, ui/src/copyable_text.tsx
___
This PR adds support for `width` property for ui.copyable_text and makes it consistent with the rest of the form components. Updated API is as follows:
```tsx
export interface CopyableText {
/** Text to be displayed inside the component. */
value: S
/** The text displayed above the textbox. */
label: S
/** An identifying name for this component. */
name?: S
/** True if the component should allow multi-line text entry. */
multiline?: B
/** Custom height in px (e.g. '200px') or '1' to fill the remaining card space. Requires `multiline` to be set. */
height?: S
/** The width of the copyable text , e.g. '100px'. */
width?: S
}
```
Closes #2282
=> feat: Add width support for copyable text #2282

broker.go, client.go, conf.go, socket.go, ui/src/core.ts, website/docs/routing.md
Reconnect feature stabilization.
This PR adds R/W synchronization to client state shared across multiple goroutines, preventing race conditions. A simple state machine is used for the synchronization.
=> fix: Eliminate race conditions in reconnect feature.

ui/src/progress_table_cell_type.test.tsx, ui/src/progress_table_cell_type.tsx
Closes #824 
As explained in the issue, the table progress cell currently rounds values to whole numbers when diplaying them as a percentage. With this change, the percentage will now render with up to 2 decimal places. This is accomplished by using toFixed(2) and parseFloat() together to ensure data is rounded properly and then trailing zeros are removed. The code change in `ui/src/progress_table_cell_type.tsx` looks like this:
```{typescript}
<div className={css.percent}>{`${Number.parseFloat((progress * 100).toFixed(2))}%`}</div>
```
Here is a partial screen shot of the Table example where you can see the progress data now being displayed with up to 2 decimal places:
There is a new test case in …
=> feat: Support decimal values in table progress cell type #824

py/h2o_lightwave/h2o_lightwave/types.py, py/h2o_lightwave/h2o_lightwave/ui.py, py/h2o_wave/h2o_wave/types.py, py/h2o_wave/h2o_wave/ui.py, r/R/ui.R, tools/intellij-plugin/src/main/resources/templates/wave-components.xml, tools/vscode-extension/component-snippets.json, ui/src/script.ts, website/docs/javascript.md
___
Adds `type` attribute to `ui.script()`. Tested manually - it loads JavaScript modules properly when `type="module"` is specified.
Closes #2331
=> feat: Support loading ESM modules using ui.script #2331

ui/src/combobox.test.tsx, ui/src/combobox.tsx
=> fix: Trigger multi combobox args after they are set, not before.

Makefile, cmd/wave/main.go, cmd/wavedb/main.go
`GOEXPERIMENT=boringcrypto` switches `crypto` packages to call BoringCrypto library. It is included as a precompiled object with Go distibution so can be linked to statically.
We want to have all  binaries consistently built this way to get closer to FIPS 140 compliance.
=> build: 🔒Enable and enforce `boringcrypto` experiment

website/docs/wavedb.md
PR #1818 moved the location of the `db.py` file. This PR adjusts sources to changes.
=> fix: update h2o wave db reference

server.go
Closes #2130
As requested in the ticket, I have made changes so that an error is thrown when an invalid public or private directory is provided when starting the wave server. The following validation was added to `server.go` in the `splitDirMapping()` function:
```go
if _, err := os.Stat(xs[1]); os.IsNotExist(err){
panic(fmt.Sprintf("directory does not exist: %s", xs[1]))
}
```
I tested the change by temporarily modifying the `run` target in the `Makefile` to have various combinations of valid and invalid values for `public-dir` and `public-dir`. Here are screen shots of a couple examples where invalid directories were given:
And here are screen shots where valid directories are provided and I also included the browser in the …
=> feat: Raise error if waved cannot find public/private dir #2130

ui/src/table.test.tsx, ui/src/table.tsx
Closes #1689
As requested in the ticket, I have updated the table component so that it will display a count of selected options just to the top right of the chevron down icon. As suggested, I used `onRenderHeader` to accomplish this - this means the custom renderer for the column now displays the name, sort icon, chevron icon and count. The code changes are in `ui/src/table.tsx` and here is a screen shot of what it looks like:
And here is a short video demonstrating the filtering after this change:
https://github.com/user-attachments/assets/fa6f7b85-4a62-40cc-bb08-834b366f4339
Question for you: The count is being rendered in red with a red border to match how the requirement is defined in the ticket. I wasn't sure if that was …
=> feat: Display active table filter count #1689

ui/src/table.test.tsx, ui/src/table.tsx
Closes #2386
I was able to find the root cause of this bug. The issue is in the definition of the `ContextualMenu` component that is used to display the column filtering options. The bug is in the `isFilterChecked` function in `ContextualMenu`:
```typescript
ContextualMenu = ({ onFilterChange, col, listProps, selectedFilters, setFiltersInBulk }: ContextualMenuProps) => {
const
isFilterChecked = (data: S, key: S) => !!selectedFilters && selectedFilters[data]?.includes(key),
[menuFilters, setMenuFilters] = React.useState(col.cellType?.tag
? Array.from(listProps.items.reduce((_filters, { key, text, data }) => {
key.split(',').forEach(key => _filters.set(key, { key, text, data, checked: isFilterChecked(data, key) }))
return …
```
=> fix: Select All on 2nd filter in table not showing checked checkboxes #2386

.github/workflows/publish-university.yml, .github/workflows/release-wave.yml, .github/workflows/wave-bundle-docker-build-publish.yaml
Description:
Updated version of Upload Artifact Github Action to v4 as v3 is deprecated by Nov 2024
reference -: https://github.com/actions/upload-artifact?tab=readme-ov-file#actionsupload-artifact
=> fix: Changed the artifact upload action version

ui/src/table.tsx
Closes #2400
I have fixed this bug, which was a regression that I introduced in PR [#2371](https://github.com/h2oai/wave/pull/2371). 
This was resolved by adding wrapping the column name in a `span` and adding styling to hide overflow text and replace with an ellipsis. The code looks like this:
```typescript
<span style={{ textOverflow: 'ellipsis', overflow: 'hidden' }}>{props.column.name}</span>
```
I made local changes to the `table.py` example to have some really long names and made sure the text is properly clipped and that sorting icon and filtering stuff still works fine. Here's a screen shot:
And here's a short video:
https://github.com/user-attachments/assets/27cc00f6-d334-49b7-bf69-282ff6518a45
I tried creating a new …
=> fix: Dropdown of filterable columns not always visible #2400

ui/src/progress_table_cell_type.test.tsx, ui/src/progress_table_cell_type.tsx
Closes #2380
I have fixed this bug relating to floating-point error when rendering the `ProgressTableCellType` component.
The bug is in `progress_table_cell_type.tsx` where the progress value is multiplied by 100. Here's a snipit of that:
```typescript
<div className={css.percent}>{`${Number.isInteger(progress * 1000) ? (progress * 100) : (progress * 100).toFixed(2)}%`}</div>
```
This bit of code can result in unexpected behavior because of floating-point arithmetic. The value `0.14` is an example of this and when multiplied by `100` it actually returns `14.000000000000002`. Here is a screen shot from the Chrome js console where I show a few examples of this happening:
Background: If you recall from the …
=> fix: progress_table_cell_type floating point rounding issues #2380

ui/src/table.test.tsx, ui/src/table.tsx
____
https://github.com/user-attachments/assets/a5b09da2-3ad0-435e-a84f-51c0e0819ead
Closes #2445
=> fix: Allow dynamic change of table selection #2445

ui/package-lock.json
Closes https://github.com/h2oai/wave/issues/2299
This is a follow up to the original: https://github.com/h2oai/wave/pull/2300 But instead leverages https://github.com/jeslie0/npm-lockfile-fix to correct the package-lock.json for all files that were missing `integrity` & `resolved` fields. This should be a noop to the existing ui build. Ultimately having these fields will harden the build process any ensure a build doesnt get unexpected (potentially malicious) dependencies from npm.
=> fix: adds missing integrity & resolved to npm package-lock.json
